// priority: 0

console.info('Hello, World! (You will only see this line once in console, during startup)')

StartupEvents.registry('item', event => {
	event.create('raw_almandine').displayName('Raw Almandine').texture("kubejs:item/raw/raw").color(0, 0xED0000)
	event.create('raw_aluminium').displayName('Raw Aluminium').texture("kubejs:item/raw/raw").color(0, 0x69A4C4)
	event.create('raw_alunite').displayName('Raw Alunite').texture("kubejs:item/raw/raw").color(0, 0xB89335)
	event.create('raw_amethyst').displayName('Raw Amethyst').texture("kubejs:item/raw/raw").color(0, 0x7B5DAF)
	event.create('raw_apatite').displayName('Raw Apatite').texture("kubejs:item/raw/raw").color(0, 0xBABAED)
	event.create('raw_asbestos').displayName('Raw Asbestos').texture("kubejs:item/raw/raw").color(0, 0xBCBCBC)
	event.create('raw_banded_iron').displayName('Raw Banded Iron').texture("kubejs:item/raw/raw").color(0, 0x845252)
	event.create('raw_barite').displayName('Raw Barite').texture("kubejs:item/raw/raw").color(0, 0xBCC0C0)
	event.create('raw_basaltic').displayName('Raw Basaltic').texture("kubejs:item/raw/raw").color(0, 0x212921)
	event.create('raw_bastnasite').displayName('Raw Bastnasite').texture("kubejs:item/raw/raw").color(0, 0x683917)
	event.create('raw_bauxite').displayName('Raw Bauxite').texture("kubejs:item/raw/raw").color(0, 0xAC5600)
	event.create('raw_bentonite').displayName('Raw Bentonite').texture("kubejs:item/raw/raw").color(0, 0x9C8985)
	event.create('raw_beryllium').displayName('Raw Beryllium').texture("kubejs:item/raw/raw").color(0, 0x5BA45B)
	event.create('raw_blue_topaz').displayName('Raw Blue Topaz').texture("kubejs:item/raw/raw").color(0, 0x3B4869)
	event.create('raw_bornite').displayName('Raw Bornite').texture("kubejs:item/raw/raw").color(0, 0x65441D)
	event.create('raw_brown_limonite').displayName('Raw Brown Limonite').texture("kubejs:item/raw/raw").color(0, 0xAE5700)
	event.create('raw_calcite').displayName('Raw Calcite').texture("kubejs:item/raw/raw").color(0, 0xCDBCB4)
	event.create('raw_cassiterite').displayName('Raw Cassiterite').texture("kubejs:item/raw/raw").color(0, 0xBFBFBF)
	event.create('raw_certus_quartz').displayName('Raw Certus Quartz').texture("kubejs:item/raw/raw").color(0, 0x797999)
	event.create('raw_chalcocite').displayName('Raw Chalcocite').texture("kubejs:item/raw/raw").color(0, 0x313131)
	event.create('raw_chalcopyrite').displayName('Raw Chalcopyrite').texture("kubejs:item/raw/raw").color(0, 0x836221)
	event.create('raw_chromite').displayName('Raw Chromite').texture("kubejs:item/raw/raw").color(0, 0x1E110D)
	event.create('raw_cinnabar').displayName('Raw Cinnabar').texture("kubejs:item/raw/raw").color(0, 0x8C0000)
	event.create('raw_coal').displayName('Raw Coal').texture("kubejs:item/raw/raw").color(0, 0x414141)
	event.create('raw_cobalt').displayName('Raw Cobalt').texture("kubejs:item/raw/raw").color(0, 0x313199)
	event.create('raw_cobaltite').displayName('Raw Cobaltite').texture("kubejs:item/raw/raw").color(0, 0x4545D8)
	event.create('raw_cooperite').displayName('Raw Cooperite').texture("kubejs:item/raw/raw").color(0, 0xDEDEAE)
	event.create('raw_copper').displayName('Raw Copper').texture("kubejs:item/raw/raw").color(0, 0x8F3800)
	event.create('raw_diamond').displayName('Raw Diamond').texture("kubejs:item/raw/raw").color(0, 0xBAEDED)
	event.create('raw_diatomite').displayName('Raw Diatomite').texture("kubejs:item/raw/raw").color(0, 0x86869C)
	event.create('raw_electrotine').displayName('Raw Electrotine').texture("kubejs:item/raw/raw").color(0, 0x37A6B8)
	event.create('raw_emerald').displayName('Raw Emerald').texture("kubejs:item/raw/raw").color(0, 0x4AED4A)
	event.create('raw_fullers_earth').displayName('Raw Fullers Earth').texture("kubejs:item/raw/raw").color(0, 0x848463)
	event.create('raw_galena').displayName('Raw Galena').texture("kubejs:item/raw/raw").color(0, 0x573457)
	event.create('raw_garnet').displayName('Raw Garnet').texture("kubejs:item/raw/raw").color(0, 0x9F4F00)
	event.create('raw_garnet_red').displayName('Raw Red Garnet').texture("kubejs:item/raw/raw").color(0, 0x602626)
	event.create('raw_garnet_yellow').displayName('Raw Yellow Garnet').texture("kubejs:item/raw/raw").color(0, 0x838334)
	event.create('raw_garnierite').displayName('Raw Garnierite').texture("kubejs:item/raw/raw").color(0, 0x2DB640)
	event.create('raw_glauconite').displayName('Raw Glauconite').texture("kubejs:item/raw/raw").color(0, 0x678F30)
	event.create('raw_gold').displayName('Raw Gold').texture("kubejs:item/raw/raw").color(0, 0xD1BC41)
	event.create('raw_granitic').displayName('Raw Granitic').texture("kubejs:item/raw/raw").color(0, 0x1E2D2D)
	event.create('raw_graphite').displayName('Raw Graphite').texture("kubejs:item/raw/raw").color(0, 0x676767)
	event.create('raw_green_sapphire').displayName('Raw Green Sapphire').texture("kubejs:item/raw/raw").color(0, 0x5DBA79)
	event.create('raw_grossular').displayName('Raw Grossular').texture("kubejs:item/raw/raw").color(0, 0xBA5D00)
	event.create('raw_gypsum').displayName('Raw Gypsum').texture("kubejs:item/raw/raw").color(0, 0xBCBCCD)
	event.create('raw_ilmenite').displayName('Raw Ilmenite').texture("kubejs:item/raw/raw").color(0, 0x3C2F2B)
	event.create('raw_iron').displayName('Raw Iron').texture("kubejs:item/raw/raw").color(0, 0xB4B4B4)
	event.create('raw_kyanite').displayName('Raw Kyanite').texture("kubejs:item/raw/raw").color(0, 0x5858C8)
	event.create('raw_lapis').displayName('Raw Lapis').texture("kubejs:item/raw/raw").color(0, 0x3838B0)
	event.create('raw_lazurite').displayName('Raw Lazurite').texture("kubejs:item/raw/raw").color(0, 0x4957C0)
	event.create('raw_lead').displayName('Raw Lead').texture("kubejs:item/raw/raw").color(0, 0x4F384F)
	event.create('raw_lepidolite').displayName('Raw Lepidolite').texture("kubejs:item/raw/raw").color(0, 0xB02567)
	event.create('raw_lithium').displayName('Raw Lithium').texture("kubejs:item/raw/raw").color(0, 0xA1AABB)
	event.create('raw_magnesite').displayName('Raw Magnesite').texture("kubejs:item/raw/raw").color(0, 0xACAC88)
	event.create('raw_magnetite').displayName('Raw Magnetite').texture("kubejs:item/raw/raw").color(0, 0x191919)
	event.create('raw_malachite').displayName('Raw Malachite').texture("kubejs:item/raw/raw").color(0, 0x678F30)
	event.create('raw_mica').displayName('Raw Mica').texture("kubejs:item/raw/raw").color(0, 0xA2A2AA)
	event.create('raw_molybdenite').displayName('Raw Molybdenite').texture("kubejs:item/raw/raw").color(0, 0x191919)
	event.create('raw_molybdenum').displayName('Raw Molybdenum').texture("kubejs:item/raw/raw").color(0, 0x65657C)
	event.create('raw_monazite').displayName('Raw Monazite').texture("kubejs:item/raw/raw").color(0, 0x314531)
	event.create('raw_naquadah').displayName('Raw Naquadah').texture("kubejs:item/raw/raw").color(0, 0x2B2B2B)
	event.create('raw_neodymium').displayName('Raw Neodymium').texture("kubejs:item/raw/raw").color(0, 0x383838)
	event.create('raw_nether_quartz').displayName('Raw Nether Quartz').texture("kubejs:item/raw/raw").color(0, 0x807584)
	event.create('raw_nickel').displayName('Raw Nickel').texture("kubejs:item/raw/raw").color(0, 0xA4A4CD)
	event.create('raw_oilsands').displayName('Raw Oilsands').texture("kubejs:item/raw/raw").color(0, 0x080808)
	event.create('raw_olivine').displayName('Raw Olivine').texture("kubejs:item/raw/raw").color(0, 0x8CED8C)
	event.create('raw_opal').displayName('Raw Opal').texture("kubejs:item/raw/raw").color(0, 0x00007A)
	event.create('raw_palladium').displayName('Raw Palladium').texture("kubejs:item/raw/raw").color(0, 0x4B4B4B)
	event.create('raw_pentlandite').displayName('Raw Pentlandite').texture("kubejs:item/raw/raw").color(0, 0x7C7104)
	event.create('raw_pitchblende').displayName('Raw Pitchblende').texture("kubejs:item/raw/raw").color(0, 0xC1CB00)
	event.create('raw_platinum').displayName('Raw Platinum').texture("kubejs:item/raw/raw").color(0, 0xE8E8B6)
	event.create('raw_plutonium').displayName('Raw Plutonium').texture("kubejs:item/raw/raw").color(0, 0xDD2E2E)
	event.create('raw_pollucite').displayName('Raw Pollucite').texture("kubejs:item/raw/raw").color(0, 0x857575)
	event.create('raw_powellite').displayName('Raw Powellite').texture("kubejs:item/raw/raw").color(0, 0xDEDE00)
	event.create('raw_pyrite').displayName('Raw Pyrite').texture("kubejs:item/raw/raw").color(0, 0x735C1F)
	event.create('raw_pyrochlore').displayName('Raw Pyrochlore').texture("kubejs:item/raw/raw").color(0, 0x270F00)
	event.create('raw_pyrolusite').displayName('Raw Pyrolusite').texture("kubejs:item/raw/raw").color(0, 0x7B7B8B)
	event.create('raw_pyrope').displayName('Raw Pyrope').texture("kubejs:item/raw/raw").color(0, 0x4E2141)
	event.create('raw_quartzite').displayName('Raw Quartzite').texture("kubejs:item/raw/raw").color(0, 0xA3B3A3)
	event.create('raw_realgar').displayName('Raw Realgar').texture("kubejs:item/raw/raw").color(0, 0x921F21)
	event.create('raw_redstone').displayName('Raw Redstone').texture("kubejs:item/raw/raw").color(0, 0x500000)
	event.create('raw_rock_salt').displayName('Raw Rock Salt').texture("kubejs:item/raw/raw").color(0, 0xBF9F9F)
	event.create('raw_ruby').displayName('Raw Ruby').texture("kubejs:item/raw/raw").color(0, 0x5B2424)
	event.create('raw_salt').displayName('Raw Salt').texture("kubejs:item/raw/raw").color(0, 0xCCCCCC)
	event.create('raw_saltpeter').displayName('Raw Saltpeter').texture("kubejs:item/raw/raw").color(0, 0xB7B7B7)
	event.create('raw_sapphire').displayName('Raw Sapphire').texture("kubejs:item/raw/raw").color(0, 0x5D5DBA)
	event.create('raw_scheelite').displayName('Raw Scheelite').texture("kubejs:item/raw/raw").color(0, 0xAE7A11)
	event.create('raw_silver').displayName('Raw Silver').texture("kubejs:item/raw/raw").color(0, 0xA7A7C2)
	event.create('raw_soapstone').displayName('Raw Soapstone').texture("kubejs:item/raw/raw").color(0, 0x4E774E)
	event.create('raw_sodalite').displayName('Raw Sodalite').texture("kubejs:item/raw/raw").color(0, 0x1010CC)
	event.create('raw_spessartine').displayName('Raw Spessartine').texture("kubejs:item/raw/raw").color(0, 0x7A3030)
	event.create('raw_sphalerite').displayName('Raw Sphalerite').texture("kubejs:item/raw/raw").color(0, 0xD1D1D1)
	event.create('raw_spodumene').displayName('Raw Spodumene').texture("kubejs:item/raw/raw").color(0, 0xB19E9E)
	event.create('raw_stibnite').displayName('Raw Stibnite').texture("kubejs:item/raw/raw").color(0, 0x3B3B3B)
	event.create('raw_sulfur').displayName('Raw Sulfur').texture("kubejs:item/raw/raw").color(0, 0xA4A400)
	event.create('raw_talc').displayName('Raw Talc').texture("kubejs:item/raw/raw").color(0, 0x428442)
	event.create('raw_tantalite').displayName('Raw Tantalite').texture("kubejs:item/raw/raw").color(0, 0x7E4623)
	event.create('raw_tetrahedrite').displayName('Raw Tetrahedrite').texture("kubejs:item/raw/raw").color(0, 0xBA1E00)
	event.create('raw_thorium').displayName('Raw Thorium').texture("kubejs:item/raw/raw").color(0, 0x001900)
	event.create('raw_tin').displayName('Raw Tin').texture("kubejs:item/raw/raw").color(0, 0xC8C8C8)
	event.create('raw_topaz').displayName('Raw Topaz').texture("kubejs:item/raw/raw").color(0, 0x7A3D00)
	event.create('raw_tricalcium_phosphate').displayName('Raw tricalcium_phosphate').texture("kubejs:item/raw/raw").color(0, 0xDCDC00)
	event.create('raw_trona').displayName('Raw Trona').texture("kubejs:item/raw/raw").color(0, 0x7E7E58)
	event.create('raw_tungstate').displayName('Raw Tungstate').texture("kubejs:item/raw/raw").color(0, 0x2E2A1D)
	event.create('raw_uraninite').displayName('Raw Uraninite').texture("kubejs:item/raw/raw").color(0, 0x191919)
	event.create('raw_vanadium_magnetite').displayName('Raw Vanadium Magnetite').texture("kubejs:item/raw/raw").color(0, 0x1E1E34)
	event.create('raw_wulfenite').displayName('Raw Wulfenite').texture("kubejs:item/raw/raw").color(0, 0xC46200)
	event.create('raw_yellow_limonite').displayName('Raw Yellow Limonite').texture("kubejs:item/raw/raw").color(0, 0x818100)
	event.create('raw_zeolite').displayName('Raw Zeolite').texture("kubejs:item/raw/raw").color(0, 0xC4BCBC)
})

