// priority: 0

console.info('Hello, World! (You will see this line every time client resources reload)')



JEIEvents.hideItems(event => {	
    // gem
    event.hide('minecraft:diamond')
    event.hide('minecraft:emerald')
    event.hide('minecraft:lapis_lazuli')
    event.hide('minecraft:amethyst_shard')
    event.hide('minecraft:raw_iron')
    event.hide('minecraft:raw_copper')
    event.hide('minecraft:raw_gold')

    // armor
    event.hide('minecraft:chainmail_helmet')
    event.hide('minecraft:chainmail_chestplate')
    event.hide('minecraft:chainmail_leggings')
    event.hide('minecraft:chainmail_boots')
    event.hide('minecraft:iron_helmet')
    event.hide('minecraft:iron_chestplate')
    event.hide('minecraft:iron_leggings')
    event.hide('minecraft:iron_boots')
    event.hide('minecraft:diamond_helmet')
    event.hide('minecraft:diamond_chestplate')
    event.hide('minecraft:diamond_leggings')
    event.hide('minecraft:diamond_boots')
    event.hide('minecraft:golden_helmet')
    event.hide('minecraft:golden_chestplate')
    event.hide('minecraft:golden_leggings')
    event.hide('minecraft:golden_boots')
    event.hide('minecraft:netherite_helmet')
    event.hide('minecraft:netherite_chestplate')
    event.hide('minecraft:netherite_leggings')
    event.hide('minecraft:netherite_boots')

    // weapons
    event.hide('minecraft:wooden_sword')
    event.hide('minecraft:wooden_shovel')
    event.hide('minecraft:wooden_pickaxe')
    event.hide('minecraft:wooden_axe')
    event.hide('minecraft:wooden_hoe')
    event.hide('minecraft:stone_sword')
    event.hide('minecraft:stone_shovel')
    event.hide('minecraft:stone_pickaxe')
    event.hide('minecraft:stone_axe')
    event.hide('minecraft:stone_hoe')
    event.hide('minecraft:iron_sword')
    event.hide('minecraft:iron_shovel')
    event.hide('minecraft:iron_pickaxe')
    event.hide('minecraft:iron_axe')
    event.hide('minecraft:iron_hoe')
    event.hide('minecraft:golden_sword')
    event.hide('minecraft:golden_shovel')
    event.hide('minecraft:golden_pickaxe')
    event.hide('minecraft:golden_axe')
    event.hide('minecraft:golden_hoe')
    event.hide('minecraft:diamond_sword')
    event.hide('minecraft:diamond_shovel')
    event.hide('minecraft:diamond_pickaxe')
    event.hide('minecraft:diamond_axe')
    event.hide('minecraft:diamond_hoe')
    event.hide('minecraft:netherite_sword')
    event.hide('minecraft:netherite_shovel')
    event.hide('minecraft:netherite_pickaxe')
    event.hide('minecraft:netherite_axe')
    event.hide('minecraft:netherite_hoe')

    // candle
    event.hide('minecraft:candle')
    event.hide('minecraft:white_candle')
    event.hide('minecraft:orange_candle')
    event.hide('minecraft:magenta_candle')
    event.hide('minecraft:light_blue_candle')
    event.hide('minecraft:yellow_candle')
    event.hide('minecraft:lime_candle')
    event.hide('minecraft:pink_candle')
    event.hide('minecraft:gray_candle')
    event.hide('minecraft:light_gray_candle')
    event.hide('minecraft:cyan_candle')
    event.hide('minecraft:purple_candle')
    event.hide('minecraft:blue_candle')
    event.hide('minecraft:brown_candle')
    event.hide('minecraft:green_candle')
    event.hide('minecraft:red_candle')
    event.hide('minecraft:black_candle')

    // heads / eggs
    event.hide('minecraft:skeleton_skull')
    event.hide('minecraft:wither_skeleton_skull')
    event.hide('minecraft:zombie_head')
    event.hide('minecraft:creeper_head')
    event.hide('minecraft:dragon_head')
    event.hide('minecraft:turtle_egg')

    // walls
    event.hide('minecraft:cobblestone_wall')	
    event.hide('minecraft:granite_wall')	
    event.hide('minecraft:prismarine_wall')	
    event.hide('minecraft:mossy_stone_brick_wall')	
    event.hide('minecraft:stone_brick_wall')	
    event.hide('minecraft:mud_brick_wall')	
    event.hide('minecraft:nether_brick_wall')	
    event.hide('minecraft:andesite_wall')	
    event.hide('minecraft:red_nether_brick_wall')	
    event.hide('minecraft:sandstone_wall')	
    event.hide('minecraft:diorite_wall')	
    event.hide('minecraft:blackstone_wall')	
    event.hide('minecraft:polished_blackstone_wall')	
    event.hide('minecraft:polished_blackstone_brick_wall')	
    
    // Sculk
    event.hide('minecraft:sculk')
    event.hide('minecraft:sculk_sensor')
    event.hide('minecraft:sculk_vein')
    event.hide('minecraft:sculk_catalyst')
    event.hide('minecraft:sculk_shrieker')
    
    // infested
    event.hide('minecraft:infested_stone')
    event.hide('minecraft:infested_cobblestone')
    event.hide('minecraft:infested_stone_bricks')
    event.hide('minecraft:infested_mossy_stone_bricks')
    event.hide('minecraft:infested_cracked_stone_bricks')
    event.hide('minecraft:infested_chiseled_stone_bricks')
    
    // blackstone
    event.hide('minecraft:blackstone')
    event.hide('minecraft:blackstone_slab')
    event.hide('minecraft:blackstone_stairs')
    event.hide('minecraft:gilded_blackstone')
    event.hide('minecraft:polished_blackstone')
    event.hide('minecraft:polished_blackstone_slab')
    event.hide('minecraft:polished_blackstone_stairs')
    event.hide('minecraft:chiseled_polished_blackstone')
    event.hide('minecraft:polished_blackstone_bricks')
    event.hide('minecraft:polished_blackstone_brick_slab')
    event.hide('minecraft:polished_blackstone_brick_stairs')
    event.hide('minecraft:cracked_polished_blackstone_bricks')

    // chest boat
    event.hide('minecraft:oak_chest_boat')
    event.hide('minecraft:spruce_chest_boat')
    event.hide('minecraft:birch_chest_boat')
    event.hide('minecraft:jungle_chest_boat')
    event.hide('minecraft:acacia_chest_boat')
    event.hide('minecraft:dark_oak_chest_boat')
    event.hide('minecraft:mangrove_chest_boat')
    event.hide('minecraft:crimson_chest_boat')

    // boat
    event.hide('minecraft:oak_boat')
    event.hide('minecraft:spruce_boat')
    event.hide('minecraft:birch_boat')
    event.hide('minecraft:jungle_boat')
    event.hide('minecraft:acacia_boat')
    event.hide('minecraft:dark_oak_boat')
    event.hide('minecraft:mangrove_boat')
    event.hide('minecraft:crimson_boat')

    // gate
    event.hide('minecraft:oak_fence_gate')
    event.hide('minecraft:spruce_fence_gate')
    event.hide('minecraft:birch_fence_gate')
    event.hide('minecraft:jungle_fence_gate')
    event.hide('minecraft:acacia_fence_gate')
    event.hide('minecraft:dark_oak_fence_gate')
    event.hide('minecraft:mangrove_fence_gate')
    event.hide('minecraft:crimson_fence_gate')
    event.hide('minecraft:warped_fence_gate')
    event.hide('minecraft:nether_brick_fence_gate')

    // trapdoor
    event.hide('minecraft:iron_trapdoor')
    event.hide('minecraft:oak_trapdoor')
    event.hide('minecraft:spruce_trapdoor')
    event.hide('minecraft:birch_trapdoor')
    event.hide('minecraft:jungle_trapdoor')
    event.hide('minecraft:acacia_trapdoor')
    event.hide('minecraft:dark_oak_trapdoor')
    event.hide('minecraft:mangrove_trapdoor')
    event.hide('minecraft:crimson_trapdoor')
    event.hide('minecraft:warped_trapdoor')
    event.hide('minecraft:nether_brick_trapdoor')

    // door
    event.hide('minecraft:iron_door')
    event.hide('minecraft:oak_door')
    event.hide('minecraft:spruce_door')
    event.hide('minecraft:birch_door')
    event.hide('minecraft:jungle_door')
    event.hide('minecraft:acacia_door')
    event.hide('minecraft:dark_oak_door')
    event.hide('minecraft:mangrove_door')
    event.hide('minecraft:crimson_door')
    event.hide('minecraft:warped_door')
    event.hide('minecraft:nether_brick_door')

    // sign
    event.hide('minecraft:oak_sign')
    event.hide('minecraft:spruce_sign')
    event.hide('minecraft:birch_sign')
    event.hide('minecraft:jungle_sign')
    event.hide('minecraft:acacia_sign')
    event.hide('minecraft:dark_oak_sign')
    event.hide('minecraft:mangrove_sign')
    event.hide('minecraft:crimson_sign')
    event.hide('minecraft:warped_sign')
    event.hide('minecraft:nether_brick_sign')

    // button
    event.hide('minecraft:oak_pressure_plate')
    event.hide('minecraft:spruce_pressure_plate')
    event.hide('minecraft:birch_pressure_plate')
    event.hide('minecraft:jungle_pressure_plate')
    event.hide('minecraft:acacia_pressure_plate')
    event.hide('minecraft:dark_oak_pressure_plate')
    event.hide('minecraft:mangrove_pressure_plate')
    event.hide('minecraft:crimson_pressure_plate')
    event.hide('minecraft:warped_pressure_plate')
    event.hide('minecraft:nether_brick_pressure_plate')
    event.hide('minecraft:stone_pressure_plate')
    event.hide('minecraft:polished_blackstone_pressure_plate')

    // button
    event.hide('minecraft:oak_button')
    event.hide('minecraft:spruce_button')
    event.hide('minecraft:birch_button')
    event.hide('minecraft:jungle_button')
    event.hide('minecraft:acacia_button')
    event.hide('minecraft:dark_oak_button')
    event.hide('minecraft:mangrove_button')
    event.hide('minecraft:crimson_button')
    event.hide('minecraft:warped_button')
    event.hide('minecraft:nether_brick_button')
    event.hide('minecraft:stone_button')
    event.hide('minecraft:polished_blackstone_button')

    // food
    event.hide('minecraft:apple')

    // spawn eggs
    event.hide('minecraft:allay_spawn_egg')
    event.hide('minecraft:axolotl_spawn_egg')
    event.hide('minecraft:bat_spawn_egg')
    event.hide('minecraft:bee_spawn_egg')
    event.hide('minecraft:blaze_spawn_egg')
    event.hide('minecraft:cat_spawn_egg')
    event.hide('minecraft:cave_spider_spawn_egg')
    event.hide('minecraft:chicken_spawn_egg')
    event.hide('minecraft:cod_spawn_egg')
    event.hide('minecraft:cow_spawn_egg')
    event.hide('minecraft:creeper_spawn_egg')
    event.hide('minecraft:dolphin_spawn_egg')
    event.hide('minecraft:donkey_spawn_egg')
    event.hide('minecraft:drowned_spawn_egg')
    event.hide('minecraft:elder_guardian_spawn_egg')
    event.hide('minecraft:enderman_spawn_egg')
    event.hide('minecraft:endermite_spawn_egg')
    event.hide('minecraft:evoker_spawn_egg')
    event.hide('minecraft:fox_spawn_egg')
    event.hide('minecraft:frog_spawn_egg')
    event.hide('minecraft:ghast_spawn_egg')
    event.hide('minecraft:glow_squid_spawn_egg')
    event.hide('minecraft:goat_spawn_egg')
    event.hide('minecraft:guardian_spawn_egg')
    event.hide('minecraft:hoglin_spawn_egg')
    event.hide('minecraft:horse_spawn_egg')
    event.hide('minecraft:husk_spawn_egg')
    event.hide('minecraft:llama_spawn_egg')
    event.hide('minecraft:magma_cube_spawn_egg')
    event.hide('minecraft:mooshroom_spawn_egg')
    event.hide('minecraft:mule_spawn_egg')
    event.hide('minecraft:ocelot_spawn_egg')
    event.hide('minecraft:panda_spawn_egg')
    event.hide('minecraft:parrot_spawn_egg')
    event.hide('minecraft:phantom_spawn_egg')
    event.hide('minecraft:pig_spawn_egg')
    event.hide('minecraft:piglin_spawn_egg')
    event.hide('minecraft:piglin_brute_spawn_egg')
    event.hide('minecraft:pillager_spawn_egg')
    event.hide('minecraft:polar_bear_spawn_egg')
    event.hide('minecraft:pufferfish_spawn_egg')
    event.hide('minecraft:rabbit_spawn_egg')
    event.hide('minecraft:ravager_spawn_egg')
    event.hide('minecraft:salmon_spawn_egg')
    event.hide('minecraft:sheep_spawn_egg')
    event.hide('minecraft:shulker_spawn_egg')
    event.hide('minecraft:silverfish_spawn_egg')
    event.hide('minecraft:skeleton_spawn_egg')
    event.hide('minecraft:skeleton_horse_spawn_egg')
    event.hide('minecraft:slime_spawn_egg')
    event.hide('minecraft:spider_spawn_egg')
    event.hide('minecraft:squid_spawn_egg')
    event.hide('minecraft:stray_spawn_egg')
    event.hide('minecraft:strider_spawn_egg')
    event.hide('minecraft:tadpole_spawn_egg')
    event.hide('minecraft:trader_llama_spawn_egg')
    event.hide('minecraft:tropical_fish_spawn_egg')
    event.hide('minecraft:turtle_spawn_egg')
    event.hide('minecraft:vex_spawn_egg')
    event.hide('minecraft:villager_spawn_egg')
    event.hide('minecraft:vindicator_spawn_egg')
    event.hide('minecraft:wandering_trader_spawn_egg')
    event.hide('minecraft:warden_spawn_egg')
    event.hide('minecraft:witch_spawn_egg')
    event.hide('minecraft:wither_skeleton_spawn_egg')
    event.hide('minecraft:wolf_spawn_egg')
    event.hide('minecraft:zoglin_spawn_egg')
    event.hide('minecraft:zombie_spawn_egg')
    event.hide('minecraft:zombie_horse_spawn_egg')
    event.hide('minecraft:zombie_villager_spawn_egg')
    event.hide('minecraft:zombified_piglin_spawn_egg')

    // fences
    event.hide('minecraft:oak_fence')
    event.hide('minecraft:spruce_fence')
    event.hide('minecraft:birch_fence')
    event.hide('minecraft:jungle_fence')
    event.hide('minecraft:acacia_fence')
    event.hide('minecraft:dark_oak_fence')
    event.hide('minecraft:mangrove_fence')
    event.hide('minecraft:crimson_fence')
    event.hide('minecraft:warped_fence')
    event.hide('minecraft:nether_brick_fence')

    // random buckets
    event.hide('minecraft:powder_snow_bucket')
    event.hide('minecraft:pufferfish_bucket')
    event.hide('minecraft:salmon_bucket')
    event.hide('minecraft:cod_bucket')
    event.hide('minecraft:tropical_fish_bucket')
    event.hide('minecraft:axolotl_bucket')
    event.hide('minecraft:tadpole_bucket')

    // food
    event.hide('minecraft:mutton')
    event.hide('minecraft:beetroot')
    event.hide('minecraft:beetroot_seeds')
    event.hide('minecraft:beetroot_soup')
    event.hide('minecraft:cooked_mutton')
    event.hide('minecraft:rabbit')
    event.hide('minecraft:cooked_rabbit')
    event.hide('minecraft:rabbit_stew')
    event.hide('minecraft:rabbit_foot')
    event.hide('minecraft:rabbit_hide')
    event.hide('minecraft:pumpkin_pie')
    event.hide('minecraft:potato')
    event.hide('minecraft:golden_carrot')
    event.hide('minecraft:poisonous_potato')
    event.hide('minecraft:baked_potato')
    event.hide('minecraft:carrot')
    event.hide('minecraft:chicken')
    event.hide('minecraft:cooked_chicken')
    event.hide('minecraft:rotten_flesh')
    event.hide('minecraft:beef')
    event.hide('minecraft:cooked_beef')
    event.hide('minecraft:porkchop')
    event.hide('minecraft:cake')
    event.hide('minecraft:cod')
    event.hide('minecraft:salmon')
    event.hide('minecraft:tropical_fish')
    event.hide('minecraft:pufferfish')
    event.hide('minecraft:cooked_cod')
    event.hide('minecraft:cooked_salmon')
    event.hide('minecraft:cooked_porkchop')
    event.hide('minecraft:golden_apple')
    event.hide('minecraft:enchanted_golden_apple')

    // disc
    event.hide('minecraft:music_disc_13')
    event.hide('minecraft:music_disc_cat')
    event.hide('minecraft:music_disc_blocks')
    event.hide('minecraft:music_disc_chirp')
    event.hide('minecraft:music_disc_far')
    event.hide('minecraft:music_disc_mall')
    event.hide('minecraft:music_disc_mellohi')
    event.hide('minecraft:music_disc_stal')
    event.hide('minecraft:music_disc_strad')
    event.hide('minecraft:music_disc_ward')
    event.hide('minecraft:music_disc_11')
    event.hide('minecraft:music_disc_wait')
    event.hide('minecraft:music_disc_otherside')
    event.hide('minecraft:music_disc_5')
    event.hide('minecraft:music_disc_pigstep')
    event.hide('minecraft:disc_fragment_5')

    // banner
    event.hide('minecraft:flower_banner_pattern')
    event.hide('minecraft:creeper_banner_pattern')
    event.hide('minecraft:skull_banner_pattern')
    event.hide('minecraft:mojang_banner_pattern')
    event.hide('minecraft:globe_banner_pattern')
    event.hide('minecraft:piglin_banner_pattern')

    // Misc
    event.hide('minecraft:coal_block')
    event.hide('minecraft:iron_nugget')
    event.hide('minecraft:spectral_arrow')
    event.hide('minecraft:totem_of_undying')
    event.hide('minecraft:iron_horse_armor')
    event.hide('minecraft:golden_horse_armor')
    event.hide('minecraft:diamond_horse_armor')
    event.hide('minecraft:prismarine_shard')
    event.hide('minecraft:prismarine_crystals')
    event.hide('minecraft:nether_brick')
    event.hide('minecraft:firework_star')
    event.hide('minecraft:glistering_melon_slice')
    event.hide('minecraft:gold_nugget')
    event.hide('minecraft:brewing_stand')
    event.hide('minecraft:blaze_rod')
    event.hide('minecraft:ghast_tear')
    event.hide('minecraft:spider_eye')
    event.hide('minecraft:fermented_spider_eye')
    event.hide('minecraft:wheat_seeds')
    event.hide('minecraft:pumpkin_seeds')
    event.hide('minecraft:melon_seeds')
    event.hide('minecraft:shears')
    event.hide('minecraft:cookie')
    event.hide('minecraft:dried_kelp')
    event.hide('minecraft:potion')
    event.hide('minecraft:pumpkin_seeds')
    event.hide('minecraft:cocoa_beans')
    event.hide('minecraft:sweet_berries')
    event.hide('minecraft:glow_berries')
    event.hide('minecraft:frogspawn')
    event.hide('minecraft:echo_shard')
    event.hide('minecraft:trident')
    event.hide('minecraft:phantom_membrane')
    event.hide('minecraft:nautilus_shell')
    event.hide('minecraft:heart_of_the_sea')
    event.hide('minecraft:lingering_potion')
    event.hide('minecraft:splash_potion')
    event.hide('minecraft:tipped_arrow')
    event.hide('minecraft:experience_bottle')
    event.hide('minecraft:recovery_compass')
    event.hide('minecraft:enchanted_book')
    event.hide('minecraft:wheat_seeds')
    event.hide('minecraft:wheat')
    event.hide('minecraft:bread')
    event.hide('minecraft:mushroom_stew')
    event.hide('minecraft:string')
    event.hide('minecraft:iron_ingot')
    event.hide('minecraft:copper_ingot')
    event.hide('minecraft:gold_ingot')
    event.hide('minecraft:netherite_ingot')
    event.hide('minecraft:netherite_scrap')
    event.hide('minecraft:light_weighted_pressure_plate')
    event.hide('minecraft:heavy_weighted_pressure_plate')
    event.hide('minecraft:verdant_froglight')
    event.hide('minecraft:conduit')
    event.hide('minecraft:turtle_helmet')
    event.hide('minecraft:scute')
    event.hide('minecraft:carrot_on_a_stick')
    event.hide('minecraft:warped_fungus_on_a_stick')
    event.hide('minecraft:elytra')
    event.hide('minecraft:ochre_froglight')
    event.hide('minecraft:small_amethyst_bud')
    event.hide('minecraft:medium_amethyst_bud')
    event.hide('minecraft:large_amethyst_bud')
    event.hide('minecraft:amethyst_cluster')
    event.hide('minecraft:bee_nest')
    event.hide('minecraft:beehive')
    event.hide('minecraft:lodestone')
    event.hide('minecraft:respawn_anchor')
    event.hide('minecraft:loom')
    event.hide('minecraft:campfire')
    event.hide('minecraft:soul_campfire')
    event.hide('minecraft:shroomlight')
    event.hide('minecraft:composter')
    event.hide('minecraft:barrel')
    event.hide('minecraft:smoker')
    event.hide('minecraft:cartography_table')
    event.hide('minecraft:fletching_table')
    event.hide('minecraft:smithing_table')
    event.hide('minecraft:grindstone')
    event.hide('minecraft:end_crystal')
    event.hide('minecraft:anvil')
    event.hide('minecraft:armor_stand')
    event.hide('minecraft:ice')
    event.hide('minecraft:chain')
    event.hide('minecraft:blast_furnace')
    event.hide('minecraft:furnace')
    event.hide('minecraft:furnace_minecart')
    event.hide('minecraft:iron_bars')
    event.hide('minecraft:chipped_anvil')
    event.hide('minecraft:damaged_anvil')
    event.hide('minecraft:bookshelf')
    event.hide('minecraft:enchanting_table')
    event.hide('minecraft:brown_mushroom_block')
    event.hide('minecraft:red_mushroom_block')
    event.hide('minecraft:mushroom_stem')
    event.hide('minecraft:soul_torch')
    event.hide('minecraft:soul_lantern')
    event.hide('minecraft:torch')
    event.hide('minecraft:farmland')
    event.hide('minecraft:cactus')
    event.hide('minecraft:jukebox')
    event.hide('minecraft:end_rod')
    event.hide('minecraft:chorus_plant')
    event.hide('minecraft:chest')
    event.hide('minecraft:trapped_chest')
    event.hide('minecraft:redstone_lamp')
    event.hide('minecraft:note_block')
    event.hide('minecraft:tnt_minecart')
    event.hide('minecraft:tnt')
    event.hide('minecraft:chorus_flower')
    event.hide('minecraft:mossy_cobblestone')
    event.hide('minecraft:mossy_cobblestone_slab')
    event.hide('minecraft:mossy_cobblestone_stairs')
    event.hide('minecraft:mossy_cobblestone_wall')
    event.hide('minecraft:pumpkin')
    event.hide('minecraft:carved_pumpkin')
    event.hide('minecraft:jack_o_lantern')
    event.hide('minecraft:netherrack')
    event.hide('minecraft:soul_sand')
    event.hide('minecraft:soul_soil')
    event.hide('minecraft:basalt')
    event.hide('minecraft:polished_basalt')
    event.hide('minecraft:smooth_basalt')
    event.hide('minecraft:glowstone')
    event.hide('minecraft:glowstone_dust')
    event.hide('minecraft:melon')
    event.hide('minecraft:melon_slice')
    event.hide('minecraft:prismarine')
    event.hide('minecraft:prismarine_bricks')
    event.hide('minecraft:dark_prismarine')
    event.hide('minecraft:prismarine_stairs')
    event.hide('minecraft:prismarine_brick_stairs')
    event.hide('minecraft:dark_prismarine_stairs')
    event.hide('minecraft:sea_lantern')
    event.hide('minecraft:nether_wart_block')
    event.hide('minecraft:warped_wart_block')
    event.hide('minecraft:red_nether_bricks')
    event.hide('minecraft:nether_wart')
    event.hide('minecraft:cobweb')
    event.hide('minecraft:crying_obsidian')

    //Coral
    event.hide('minecraft:dead_tube_coral_block')
    event.hide('minecraft:dead_brain_coral_block')
    event.hide('minecraft:dead_bubble_coral_block')
    event.hide('minecraft:dead_fire_coral_block')
    event.hide('minecraft:dead_horn_coral_block')
    event.hide('minecraft:tube_coral_block')
    event.hide('minecraft:brain_coral_block')
    event.hide('minecraft:bubble_coral_block')
    event.hide('minecraft:fire_coral_block')
    event.hide('minecraft:horn_coral_block')
    event.hide('minecraft:dead_tube_coral_fan')
    event.hide('minecraft:dead_brain_coral_fan')
    event.hide('minecraft:dead_bubble_coral_fan')
    event.hide('minecraft:dead_fire_coral_fan')
    event.hide('minecraft:dead_horn_coral_fan')
    event.hide('minecraft:tube_coral_fan')
    event.hide('minecraft:brain_coral_fan')
    event.hide('minecraft:bubble_coral_fan')
    event.hide('minecraft:fire_coral_fan')
    event.hide('minecraft:horn_coral_fan')
    event.hide('minecraft:tube_coral')
    event.hide('minecraft:brain_coral')
    event.hide('minecraft:bubble_coral')
    event.hide('minecraft:fire_coral')
    event.hide('minecraft:horn_coral')
    event.hide('minecraft:dead_tube_coral')
    event.hide('minecraft:dead_brain_coral')
    event.hide('minecraft:dead_bubble_coral')
    event.hide('minecraft:dead_fire_coral')
    event.hide('minecraft:dead_horn_coral')

    // Flowers			
    event.hide('minecraft:dandelion')
    event.hide('minecraft:poppy')
    event.hide('minecraft:blue_orchid')
    event.hide('minecraft:allium')
    event.hide('minecraft:azure_bluet')
    event.hide('minecraft:red_tulip')
    event.hide('minecraft:orange_tulip')
    event.hide('minecraft:white_tulip')
    event.hide('minecraft:pink_tulip')
    event.hide('minecraft:oxeye_daisy')
    event.hide('minecraft:cornflower')
    event.hide('minecraft:lily_of_the_valley')
    event.hide('minecraft:wither_rose')
    event.hide('minecraft:spore_blossom')
    event.hide('minecraft:brown_mushroom')
    event.hide('minecraft:red_mushroom')
    event.hide('minecraft:crimson_fungus')
    event.hide('minecraft:warped_fungus')
    event.hide('minecraft:crimson_roots')
    event.hide('minecraft:warped_roots')
    event.hide('minecraft:nether_sprouts')
    event.hide('minecraft:weeping_vines')
    event.hide('minecraft:twisting_vines')
    event.hide('minecraft:lilac')
    event.hide('minecraft:rose_bush')
    event.hide('minecraft:peony')
    event.hide('minecraft:tall_grass')
    event.hide('minecraft:sunflower')
    event.hide('minecraft:large_fern')
    
    // saplings  
    event.hide('minecraft:oak_sapling')
    event.hide('minecraft:spruce_sapling')
    event.hide('minecraft:birch_sapling')
    event.hide('minecraft:jungle_sapling')
    event.hide('minecraft:acacia_sapling')
    event.hide('minecraft:dark_oak_sapling')
    event.hide('minecraft:mangrove_propagule')
    
    // plants  
    event.hide('minecraft:grass')
    event.hide('minecraft:fern')
    event.hide('minecraft:azalea')
    event.hide('minecraft:flowering_azalea')
    event.hide('minecraft:dead_bush')
    event.hide('minecraft:seagrass')
    event.hide('minecraft:sea_pickle')
    event.hide('minecraft:sugar_cane')
    event.hide('minecraft:kelp')
    event.hide('minecraft:moss_carpet')
    event.hide('minecraft:moss_block')
    event.hide('minecraft:hanging_roots')
    event.hide('minecraft:big_dripleaf')
    event.hide('minecraft:small_dripleaf')
    event.hide('minecraft:vine')
    event.hide('minecraft:glow_lichen')
    event.hide('minecraft:lily_pad')

    // leaves  
    event.hide('minecraft:oak_leaves')
    event.hide('minecraft:spruce_leaves')
    event.hide('minecraft:birch_leaves')
    event.hide('minecraft:jungle_leaves')
    event.hide('minecraft:acacia_leaves')
    event.hide('minecraft:dark_oak_leaves')
    event.hide('minecraft:mangrove_leaves')
    event.hide('minecraft:azalea_leaves')
    event.hide('minecraft:flowering_azalea_leaves')

    
    // wood slab 
    event.hide('minecraft:oak_slab')
    event.hide('minecraft:spruce_slab')
    event.hide('minecraft:birch_slab')
    event.hide('minecraft:jungle_slab')
    event.hide('minecraft:acacia_slab')
    event.hide('minecraft:dark_oak_slab')
    event.hide('minecraft:mangrove_slab')
    event.hide('minecraft:crimson_slab')
    event.hide('minecraft:warped_slab')

//  slab 
    event.hide('minecraft:stone_slab')
    event.hide('minecraft:smooth_stone')
    event.hide('minecraft:smooth_stone_slab')
    event.hide('minecraft:petrified_oak_slab')
    event.hide('minecraft:cobblestone_slab')
    event.hide('minecraft:stone_brick_slab')
    event.hide('minecraft:mud_brick_slab')
    event.hide('minecraft:nether_brick_slab')
    event.hide('minecraft:prismarine_slab')
    event.hide('minecraft:prismarine_brick_slab')
    event.hide('minecraft:dark_prismarine_slab')
    event.hide('minecraft:polished_granite_slab')
    event.hide('minecraft:mossy_stone_brick_slab')
    event.hide('minecraft:polished_diorite_slab')
    event.hide('minecraft:granite_slab')
    event.hide('minecraft:andesite_slab')
    event.hide('minecraft:red_nether_brick_slab')
    event.hide('minecraft:polished_andesite_slab')
    event.hide('minecraft:diorite_slab')



    // raw
    event.hide('minecraft:raw_iron_block')
    event.hide('minecraft:raw_copper_block')
    event.hide('minecraft:raw_gold_block')
    event.hide('minecraft:budding_amethyst')

    // ore
    event.hide('minecraft:ancient_debris')
    event.hide('minecraft:coal_ore')
    event.hide('minecraft:iron_ore')
    event.hide('minecraft:copper_ore')
    event.hide('minecraft:gold_ore')
    event.hide('minecraft:redstone_ore')
    event.hide('minecraft:emerald_ore')
    event.hide('minecraft:lapis_ore')
    event.hide('minecraft:diamond_ore')
    event.hide('minecraft:nether_gold_ore')
    event.hide('minecraft:nether_quartz_ore')


    // wood
    event.hide('minecraft:oak_planks')
    event.hide('minecraft:spruce_planks')
    event.hide('minecraft:birch_planks')
    event.hide('minecraft:jungle_planks')
    event.hide('minecraft:acacia_planks')
    event.hide('minecraft:dark_oak_planks')
    event.hide('minecraft:mangrove_planks')
    event.hide('minecraft:crimson_planks')
    event.hide('minecraft:warped_planks')    
    event.hide('minecraft:oak_log')
    event.hide('minecraft:spruce_log')
    event.hide('minecraft:birch_log')
    event.hide('minecraft:jungle_log')
    event.hide('minecraft:acacia_log')
    event.hide('minecraft:dark_oak_log')
    event.hide('minecraft:mangrove_log')
    event.hide('minecraft:mangrove_roots')
    event.hide('minecraft:muddy_mangrove_roots')
    event.hide('minecraft:crimson_stem')
    event.hide('minecraft:warped_stem')    
    event.hide('minecraft:stripped_oak_log')
    event.hide('minecraft:stripped_spruce_log')
    event.hide('minecraft:stripped_birch_log')
    event.hide('minecraft:stripped_jungle_log')
    event.hide('minecraft:stripped_acacia_log')
    event.hide('minecraft:stripped_dark_oak_log')
    event.hide('minecraft:stripped_mangrove_log')
    event.hide('minecraft:stripped_crimson_stem')
    event.hide('minecraft:stripped_warped_stem')
    event.hide('minecraft:stripped_oak_wood')
    event.hide('minecraft:stripped_spruce_wood')
    event.hide('minecraft:stripped_birch_wood')
    event.hide('minecraft:stripped_jungle_wood')
    event.hide('minecraft:stripped_acacia_wood')
    event.hide('minecraft:stripped_dark_oak_wood')
    event.hide('minecraft:stripped_mangrove_wood')
    event.hide('minecraft:stripped_crimson_hyphae')
    event.hide('minecraft:stripped_warped_hyphae')
    event.hide('minecraft:oak_wood')
    event.hide('minecraft:spruce_wood')
    event.hide('minecraft:birch_wood')
    event.hide('minecraft:jungle_wood')
    event.hide('minecraft:acacia_wood')
    event.hide('minecraft:dark_oak_wood')
    event.hide('minecraft:mangrove_wood')
    event.hide('minecraft:crimson_hyphae')
    event.hide('minecraft:warped_hyphae')
    event.hide('minecraft:oak_stairs')
    event.hide('minecraft:spruce_stairs')
    event.hide('minecraft:birch_stairs')
    event.hide('minecraft:jungle_stairs')
    event.hide('minecraft:acacia_stairs')
    event.hide('minecraft:dark_oak_stairs')
    event.hide('minecraft:mangrove_stairs')
    event.hide('minecraft:crimson_stairs')
    event.hide('minecraft:warped_stairs')

    // standstone 
    event.hide('minecraft:sandstone')
    event.hide('minecraft:chiseled_sandstone')
    event.hide('minecraft:cut_sandstone')
    event.hide('minecraft:sandstone_slab')
    event.hide('minecraft:cut_sandstone_slab')
    event.hide('minecraft:red_sandstone_slab')
    event.hide('minecraft:cut_red_sandstone_slab')
    event.hide('minecraft:smooth_red_sandstone')
    event.hide('minecraft:smooth_sandstone')
    event.hide('minecraft:sandstone_stairs')
    event.hide('minecraft:red_sandstone')
    event.hide('minecraft:chiseled_red_sandstone')
    event.hide('minecraft:cut_red_sandstone')
    event.hide('minecraft:red_sandstone_stairs')
    event.hide('minecraft:smooth_red_sandstone')
    event.hide('minecraft:smooth_sandstone_stairs')
    event.hide('minecraft:smooth_red_sandstone_slab')
    event.hide('minecraft:smooth_sandstone_slab')
    event.hide('minecraft:red_sandstone_wall')
    event.hide('minecraft:sanstone_wall')

    // stone/cobble/gravel/sand
    event.hide('minecraft:bedrock')
    event.hide('minecraft:cobble')
    event.hide('minecraft:cobblestone_stairs')
    event.hide('minecraft:sand')
    event.hide('minecraft:red_sand')
    event.hide('minecraft:gravel')
    event.hide('minecraft:stone')
    event.hide('minecraft:granite')
    event.hide('minecraft:polished_granite')
    event.hide('minecraft:diorite')
    event.hide('minecraft:polished_diorite')
    event.hide('minecraft:andesite')
    event.hide('minecraft:polished_andesite')
    event.hide('minecraft:calcite')
    event.hide('minecraft:tuff')
    event.hide('minecraft:cobblestone')
    event.hide('minecraft:stone_bricks')
    event.hide('minecraft:stone_bricks_stairs')
    event.hide('minecraft:mossy_stone_bricks')
    event.hide('minecraft:cracked_stone_bricks')
    event.hide('minecraft:chiseled_stone_bricks')
    event.hide('minecraft:packed_mud')
    event.hide('minecraft:mud_bricks')
    event.hide('minecraft:mud_bricks_stairs')
    event.hide('minecraft:nether_bricks')
    event.hide('minecraft:cracked_nether_bricks')
    event.hide('minecraft:chiseled_nether_bricks')
    event.hide('minecraft:nether_brick_stairs')
    event.hide('minecraft:stone_brick_stairs')
    event.hide('minecraft:mud_brick_stairs')
    event.hide('minecraft:polished_granite_stairs')
    event.hide('minecraft:smooth_red_sandstone_stairs')
    event.hide('minecraft:mossy_stone_brick_stairs')
    event.hide('minecraft:polished_diorite_stairs')
    event.hide('minecraft:stone_stairs')
    event.hide('minecraft:granite_stairs')
    event.hide('minecraft:andesite_stairs')
    event.hide('minecraft:red_nether_brick_stairs')
    event.hide('minecraft:polished_andesite_stairs')
    event.hide('minecraft:diorite_stairs')

    // Grass/Dirt
    event.hide('minecraft:grass_block')
    event.hide('minecraft:dirt')
    event.hide('minecraft:coarse_dirt')
    event.hide('minecraft:podzol')
    event.hide('minecraft:rooted_dirt')
    event.hide('minecraft:mud')
    event.hide('minecraft:crimson_nylium')
    event.hide('minecraft:warped_nylium')
    event.hide('minecraft:mycelium')
    event.hide('minecraft:dirt_path')
    
    // DripStone
    event.hide('minecraft:dripstone_block')
    event.hide('minecraft:pointed_dripstone')

    // Deepslate
    event.hide('minecraft:deepslate')
    event.hide('minecraft:cobbled_deepslate')
    event.hide('minecraft:polished_deepslate')
    event.hide('minecraft:deepslate_coal_ore')
    event.hide('minecraft:deepslate_iron_ore')
    event.hide('minecraft:deepslate_copper_ore')
    event.hide('minecraft:deepslate_gold_ore')
    event.hide('minecraft:deepslate_redstone_ore')
    event.hide('minecraft:deepslate_emerald_ore')
    event.hide('minecraft:deepslate_lapis_ore')
    event.hide('minecraft:deepslate_diamond_ore')
    event.hide('minecraft:deepslate_bricks')
    event.hide('minecraft:cracked_deepslate_bricks')
    event.hide('minecraft:deepslate_tiles')
    event.hide('minecraft:cracked_deepslate_tiles')
    event.hide('minecraft:chiseled_deepslate')
    event.hide('minecraft:reinforced_deepslate')
    event.hide('minecraft:cobbled_deepslate_stairs')
    event.hide('minecraft:polished_deepslate_stairs')
    event.hide('minecraft:deepslate_brick_stairs')
    event.hide('minecraft:deepslate_tile_stairs')
    event.hide('minecraft:cobbled_deepslate_slab')
    event.hide('minecraft:polished_deepslate_slab')
    event.hide('minecraft:deepslate_brick_slab')
    event.hide('minecraft:deepslate_tile_slab')
    event.hide('minecraft:infested_deepslate')
    event.hide('minecraft:cobbled_deepslate_wall')
    event.hide('minecraft:polished_deepslate_wall')
    event.hide('minecraft:deepslate_brick_wall')
    event.hide('minecraft:deepslate_tile_wall')
})