
// Listen to server recipe event
ServerEvents.recipes(event => {
	// Remove broken recipes from vanilla and other mods
	// This is on by default, so you don't need this line
	//event.removeBrokenRecipes = true

    // glazed terracotta
	event.remove({id: 'gtceu:alloy_smelter/magnesium_dust_and_aluminium_dust_into_magnalium'})
	event.remove({id: 'gtceu:alloy_smelter/magnesium_dust_and_aluminium_ingot_into_magnalium'})
    event.remove({id: 'minecraft:white_glazed_terracotta'})
    event.remove({id: 'minecraft:orange_glazed_terracotta'})
    event.remove({id: 'minecraft:magenta_glazed_terracotta'})
    event.remove({id: 'minecraft:light_blue_glazed_terracotta'})
    event.remove({id: 'minecraft:yellow_glazed_terracotta'})
    event.remove({id: 'minecraft:lime_glazed_terracotta'})
    event.remove({id: 'minecraft:pink_glazed_terracotta'})
    event.remove({id: 'minecraft:gray_glazed_terracotta'})
    event.remove({id: 'minecraft:light_gray_glazed_terracotta'})
    event.remove({id: 'minecraft:cyan_glazed_terracotta'})
    event.remove({id: 'minecraft:purple_glazed_terracotta'})
    event.remove({id: 'minecraft:blue_glazed_terracotta'})
    event.remove({id: 'minecraft:brown_glazed_terracotta'})
    event.remove({id: 'minecraft:green_glazed_terracotta'})
    event.remove({id: 'minecraft:red_glazed_terracotta'})
    event.remove({id: 'minecraft:black_glazed_terracotta'})

    // candle
    event.remove({id: 'minecraft:candle'})
    event.remove({id: 'minecraft:white_candle'})
    event.remove({id: 'minecraft:orange_candle'})
    event.remove({id: 'minecraft:magenta_candle'})
    event.remove({id: 'minecraft:light_blue_candle'})
    event.remove({id: 'minecraft:yellow_candle'})
    event.remove({id: 'minecraft:lime_candle'})
    event.remove({id: 'minecraft:pink_candle'})
    event.remove({id: 'minecraft:gray_candle'})
    event.remove({id: 'minecraft:light_gray_candle'})
    event.remove({id: 'minecraft:cyan_candle'})
    event.remove({id: 'minecraft:purple_candle'})
    event.remove({id: 'minecraft:blue_candle'})
    event.remove({id: 'minecraft:brown_candle'})
    event.remove({id: 'minecraft:green_candle'})
    event.remove({id: 'minecraft:red_candle'})
    event.remove({id: 'minecraft:black_candle'})


	// Bed

	event.remove({id: 'minecraft:orange_bed_from_white_bed'})
	event.remove({id: 'minecraft:magenta_bed_from_white_bed'})
	event.remove({id: 'minecraft:light_blue_bed_from_white_bed'})
	event.remove({id: 'minecraft:yellow_bed_from_white_bed'})
	event.remove({id: 'minecraft:lime_bed_from_white_bed'})
	event.remove({id: 'minecraft:pink_bed_from_white_bed'})
	event.remove({id: 'minecraft:gray_bed_from_white_bed'})
	event.remove({id: 'minecraft:light_gray_bed_from_white_bed'})
	event.remove({id: 'minecraft:cyan_bed_from_white_bed'})
	event.remove({id: 'minecraft:purple_bed_from_white_bed'})
	event.remove({id: 'minecraft:blue_bed_from_white_bed'})
	event.remove({id: 'minecraft:brown_bed_from_white_bed'})
	event.remove({id: 'minecraft:green_bed_from_white_bed'})
	event.remove({id: 'minecraft:red_bed_from_white_bed'})
	event.remove({id: 'minecraft:black_bed_from_white_bed'})

    // cart
    event.remove({id: 'minecraft:minecart'})

    // rails
    event.remove({id: 'minecraft:powered_rail'})
    event.remove({id: 'minecraft:dector_rail'})
    event.remove({id: 'minecraft:rail'})
    event.remove({id: 'minecraft:activator_rail'})

    // netheriteScrap
    event.remove({input: 'minecraft:netherite_scrap'})
    event.remove({output: 'minecraft:netherite_scrap'})

    // boat
    event.remove({input: 'minecraft:oak_boat'})
    event.remove({input: 'minecraft:spruce_boat'})
    event.remove({input: 'minecraft:birch_boat'})
    event.remove({input: 'minecraft:jungle_boat'})
    event.remove({input: 'minecraft:acacia_boat'})
    event.remove({input: 'minecraft:dark_oak_boat'})
    event.remove({input: 'minecraft:mangrove_boat'})
    event.remove({input: 'minecraft:crimson_boat'})

	// Misc

	event.remove({input: 'minecraft:gold_ingot'})
	event.remove({input: 'minecraft:diamond'})
	event.remove({input: 'minecraft:iron_ingot'})

	
	// dye
	event.remove({id: 'minecraft:brown_dye'})
	event.remove({id: 'minecraft:white_dye'})
	event.remove({id: 'minecraft:orange_dye_from_red_yellow'})
	event.remove({id: 'minecraft:magenta_dye_from_blue_red_white_dye'})
	event.remove({id: 'minecraft:magenta_dye_from_blue_red_pink'})
	event.remove({id: 'minecraft:magenta_dye_from_purple_and_pink'})
	event.remove({id: 'minecraft:light_blue_dye_from_blue_white_dye'})
	event.remove({id: 'minecraft:lime_dye'})
	event.remove({id: 'minecraft:pink_dye_from_red_white_dye'})
	event.remove({id: 'minecraft:gray_dye'})
	event.remove({id: 'minecraft:light_gray_dye_from_gray_white_dye'})
	event.remove({id: 'minecraft:light_gray_dye_from_black_white_dye'})
	event.remove({id: 'minecraft:cyan_dye'})
	event.remove({id: 'minecraft:purple_dye'})
	event.remove({id: 'minecraft:blue_dye'})
	event.remove({id: 'minecraft:red_dye_from_beetroot'})
	event.remove({id: 'minecraft:black_dye'})
	event.remove({id: 'minecraft:bone_meal_from_bone_block'})
	event.remove({id: 'minecraft:sugar_from_honey_bottle'})

	
	// bowl
	event.remove({input: 'minecraft:brown_mushroom'})
	event.remove({input: 'minecraft:red_mushroom'})

	// food
	event.remove({id: 'minecraft:cooked_chicken_from_smoking'})
	event.remove({id: 'minecraft:cooked_beef_from_smoking'})
	event.remove({id: 'minecraft:cooked_cod_from_smoking'})
	event.remove({id: 'minecraft:cooked_salmon_from_smoking'})
	event.remove({id: 'minecraft:cooked_porkchop_from_smoking'})
	event.remove({id: 'minecraft:cooked_chicken'})
	event.remove({id: 'minecraft:cooked_rabbit'})
	event.remove({id: 'minecraft:cooked_beef'})
	event.remove({id: 'minecraft:cooked_cod'})
	event.remove({id: 'minecraft:cooked_mutton'})
	event.remove({id: 'minecraft:cooked_salmon'})
	event.remove({id: 'minecraft:cooked_porkchop'})
	event.remove({id: 'minecraft:mojang_banner_pattern'})
	event.remove({id: 'minecraft:bread'})
	event.remove({id: 'minecraft:cookie'})
	event.remove({id: 'minecraft:cake'})
	event.remove({id: 'minecraft:beetroot_soup'})
	event.remove({id: 'minecraft:baked_potato'})
	
	// Misc
	event.remove({id: 'minecraft:iron_nugget_from_smelting'})
	event.remove({id: 'minecraft:iron_nugget_from_blasting'})
	event.remove({id: 'minecraft:leather_horse_armor'})
	event.remove({id: 'minecraft:gold_nugget_from_smelting'})
	event.remove({id: 'minecraft:lead'})
	event.remove({id: 'minecraft:map'})
	event.remove({id: 'minecraft:leather'})
	event.remove({id: 'minecraft:fire_charge'})
	event.remove({id: 'minecraft:gold_nugget_from_smelting'})
	event.remove({id: 'minecraft:dried_kelp'})
	event.remove({id: 'minecraft:golden_carrot'})
	event.remove({id: 'minecraft:blaze_powder'})
	event.remove({id: 'minecraft:compass'})
	event.remove({id: 'minecraft:clock'})
	event.remove({id: 'minecraft:spyglass'})
	event.remove({id: 'minecraft:hopper'})
	event.remove({id: 'minecraft:gold_ingot_from_nuggets'})
	event.remove({id: 'minecraft:gold_ingot_from_gold_block'})
	event.remove({id: 'minecraft:netherite_ingot_from_netherite_block'})
	event.remove({id: 'minecraft:copper_ingot_from_waxed_copper_block'})
	event.remove({id: 'minecraft:copper_ingot'})
	event.remove({id: 'minecraft:iron_ingot_from_iron_block'})
	event.remove({id: 'minecraft:iron_ingot_from_nuggets'})
	event.remove({id: 'minecraft:diamond'})
	event.remove({id: 'minecraft:emerald'})
	event.remove({id: 'minecraft:lapis_lazuli'})
	event.remove({id: 'minecraft:arrow'})
	event.remove({id: 'minecraft:wheat'})
	event.remove({id: 'minecraft:coal_block'})
	event.remove({id: 'minecraft:coal'})
	event.remove({id: 'minecraft:bow'})
	event.remove({id: 'minecraft:turtle_helmet'})
	event.remove({id: 'minecraft:conduit'})
	event.remove({id: 'minecraft:carrot_on_a_stick'})
	event.remove({id: 'minecraft:light_weighted_pressure_plate'})
	event.remove({id: 'minecraft:heavy_weighted_pressure_plate'})
	event.remove({id: 'minecraft:iron_trapdoor'})
	event.remove({id: 'minecraft:lightning_rod'})
	event.remove({id: 'minecraft:iron_door'})
	event.remove({id: 'minecraft:painting'})
	event.remove({id: 'minecraft:lantern'})
	event.remove({id: 'minecraft:item_frame'})
	event.remove({id: 'minecraft:end_crystal'})
	event.remove({id: 'minecraft:tnt_minecart'})

	// chest

	event.remove({input: 'minecraft:chest'})
	event.remove({input: 'minecraft:trapped_chest'})

	// Remove Glass Id
		event.remove({id: 'minecraft:white_stained_glass_pane_from_glass_pane'})
		event.remove({id: 'minecraft:orange_stained_glass_pane_from_glass_pane'})
		event.remove({id: 'minecraft:magenta_stained_glass_pane_from_glass_pane'})
		event.remove({id: 'minecraft:light_blue_stained_glass_pane_from_glass_pane'})
		event.remove({id: 'minecraft:yellow_stained_glass_pane_from_glass_pane'})
		event.remove({id: 'minecraft:lime_stained_glass_pane_from_glass_pane'})
		event.remove({id: 'minecraft:pink_stained_glass_pane_from_glass_pane'})
		event.remove({id: 'minecraft:gray_stained_glass_pane_from_glass_pane'})
		event.remove({id: 'minecraft:light_gray_stained_glass_pane_from_glass_pane'})
		event.remove({id: 'minecraft:cyan_stained_glass_pane_from_glass_pane'})
		event.remove({id: 'minecraft:purple_stained_glass_pane_from_glass_pane'})
		event.remove({id: 'minecraft:blue_stained_glass_pane_from_glass_pane'})
		event.remove({id: 'minecraft:brown_stained_glass_pane_from_glass_pane'})
		event.remove({id: 'minecraft:green_stained_glass_pane_from_glass_pane'})
		event.remove({id: 'minecraft:red_stained_glass_pane_from_glass_pane'})
		event.remove({id: 'minecraft:black_stained_glass_pane_from_glass_pane'})

		// Netherack Input

		event.remove({input: 'minecraft:nether_bricks'})
		event.remove({input: 'minecraft:cracked_nether_bricks'})
		event.remove({input: 'minecraft:chiseled_nether_bricks'})
		event.remove({input: 'minecraft:nether_brick_stairs'})

		// Netherack Output
		event.remove({output: 'minecraft:nether_bricks'})
		event.remove({output: 'minecraft:cracked_nether_bricks'})
		event.remove({output: 'minecraft:chiseled_nether_bricks'})
		event.remove({output: 'minecraft:nether_brick_stairs'})
		event.remove({output: 'minecraft:red_nether_brick_stairs'})

		// Misc By Input

		event.remove({input: 'minecraft:raw_iron'})
		event.remove({input: 'minecraft:raw_copper'})
		event.remove({input: 'minecraft:raw_gold'})
		event.remove({input: 'minecraft:netherrack'})
		event.remove({input: 'minecraft:soul_sand'})
		event.remove({input: 'minecraft:soul_soil'})
		event.remove({input: 'minecraft:glowstone_dust'})
		event.remove({input: 'minecraft:glowstone'})
		event.remove({input: 'minecraft:stone_bricks'})
		event.remove({input: 'minecraft:mossy_stone_bricks'})
		event.remove({input: 'minecraft:cracked_stone_bricks'})
		event.remove({input: 'minecraft:chiseled_stone_bricks'})
		event.remove({input: 'minecraft:packed_mud'})
		event.remove({input: 'minecraft:mud_bricks'})
		event.remove({input: 'minecraft:melon_slice'})
		event.remove({input: 'minecraft:nether_wart'})

		// Misc By Output

		event.remove({output: 'minecraft:glowstone_dust'})
		event.remove({output: 'minecraft:glowstone'})
		event.remove({output: 'minecraft:stone_bricks'})
		event.remove({output: 'minecraft:mossy_stone_bricks'})
		event.remove({output: 'minecraft:cracked_stone_bricks'})
		event.remove({output: 'minecraft:chiseled_stone_bricks'})
		event.remove({input: 'minecraft:melon'})
		//event.remove({output: 'minecraft:'})

		// Basalt Input

		event.remove({input: 'minecraft:basalt'})
		event.remove({input: 'minecraft:polished_basalt'})
		event.remove({input: 'minecraft:smooth_basalt'})

		// Basalt Output

		event.remove({output: 'minecraft:basalt'})
		event.remove({output: 'minecraft:polished_basalt'})
		event.remove({output: 'minecraft:smooth_basalt'})


		// Remove By Id
			event.remove({id: 'minecraft:recovery_compass'})
			event.remove({id: 'minecraft:fishing_rod'})
			event.remove({id: 'minecraft:magenta_dye_from_lilac'})
			event.remove({id: 'minecraft:blast_furnace'})
			event.remove({id: 'minecraft:furnace_minecraft'})
			event.remove({id: 'minecraft:red_dye_from_rose_bush'})
			event.remove({id: 'minecraft:pink_dye_from_peony'})
			event.remove({id: 'minecraft:lodestone'})
			event.remove({id: 'minecraft:soul_lantern'})
			event.remove({id: 'minecraft:ladder'})
			event.remove({id: 'minecraft:torch'})
			event.remove({id: 'minecraft:stick_from_bamboo_item'})
			event.remove({id: 'minecraft:end_rod'})
			event.remove({id: 'minecraft:scaffolding'})
			event.remove({id: 'minecraft:moss_carpet'})
			event.remove({id: 'minecraft:netherite_ingot'})
			event.remove({id: 'minecraft:iron_block'})
			event.remove({id: 'minecraft:anvil'})
			event.remove({id: 'minecraft:copper_block'})
			event.remove({id: 'minecraft:gold_block'})
			event.remove({id: 'minecraft:green_dye'})
			event.remove({id: 'minecraft:diamond_block'})
			event.remove({id: 'minecraft:copper_ingot_from_blasting_copper'})
			event.remove({id: 'minecraft:brick_wall'})
			event.remove({id: 'minecraft:brick_slab'})
			event.remove({id: 'minecraft:brick_stairs'})
			event.remove({id: 'minecraft:lapis_block'})
			event.remove({id: 'minecraft:enchanting_table'})
			event.remove({id: 'minecraft:purpur_stairs'})
			event.remove({id: 'minecraft:purpur_slab'})
			event.remove({id: 'minecraft:purpur_pillar'})
			event.remove({id: 'minecraft:pumpkin_seeds'})
			event.remove({id: 'minecraft:pumpkin_pie'})
			event.remove({id: 'minecraft:jack_o_lantern'})
			event.remove({id: 'minecraft:end_stone_bricks'})
			event.remove({id: 'minecraft:end_stone_brick_stairs'})
			event.remove({id: 'minecraft:end_stone_brick_slab'})
			event.remove({id: 'minecraft:end_stone_brick_wall'})
			event.remove({id: 'minecraft:emerald_block'})
			event.remove({id: 'minecraft:quartz_block'})
			event.remove({id: 'minecraft:quartz_slab'})
			event.remove({id: 'minecraft:chiseled_quartz_block'})
			event.remove({id: 'minecraft:smooth_quartz_stairs'})
			event.remove({id: 'minecraft:smooth_quartz_slab'})
			event.remove({id: 'minecraft:quartz_stairs'})
			event.remove({id: 'minecraft:quartz_bricks'})
			event.remove({id: 'minecraft:quartz_pillar'})
			event.remove({id: 'minecraft:hay_block'})
			event.remove({id: 'minecraft:prismarine'})
			event.remove({id: 'minecraft:prismarine_slab'})
			event.remove({id: 'minecraft:prismarine_wall'})
			event.remove({id: 'minecraft:prismarine_bricks'})
			event.remove({id: 'minecraft:dark_prismarine'})
			event.remove({id: 'minecraft:prismarine_stairs'})
			event.remove({id: 'minecraft:prismarine_brick_stairs'})
			event.remove({id: 'minecraft:dark_prismarine_stairs'})
			event.remove({id: 'minecraft:sea_lantern'})
			event.remove({id: 'minecraft:nether_wart_block'})
			event.remove({id: 'minecraft:red_nether_bricks'})
			event.remove({id: 'minecraft:dried_kelp_block'})
			event.remove({id: 'minecraft:lime_dye_from_smelting'})

			event.remove({output: 'minecraft:prismarine', type: 'minecraft:stonecutting'})
			event.remove({output: 'minecraft:prismarine_slab', type: 'minecraft:stonecutting'})
			event.remove({output: 'minecraft:prismarine_wall', type: 'minecraft:stonecutting'})
			event.remove({output: 'minecraft:prismarine_bricks', type: 'minecraft:stonecutting'})
			event.remove({output: 'minecraft:dark_prismarine', type: 'minecraft:stonecutting'})
			event.remove({output: 'minecraft:prismarine_stairs', type: 'minecraft:stonecutting'})
			event.remove({output: 'minecraft:prismarine_brick_stairs', type: 'minecraft:stonecutting'})
			event.remove({output: 'minecraft:dark_prismarine_stairs', type: 'minecraft:stonecutting'})
			

		// Terracotta by ID
			event.remove({id: 'minecraft:white_terracotta'})
			event.remove({id: 'minecraft:orange_terracotta'})
			event.remove({id: 'minecraft:magenta_terracotta'})
			event.remove({id: 'minecraft:light_blue_terracotta'})
			event.remove({id: 'minecraft:yellow_terracotta'})
			event.remove({id: 'minecraft:lime_terracotta'})
			event.remove({id: 'minecraft:pink_terracotta'})
			event.remove({id: 'minecraft:gray_terracotta'})
			event.remove({id: 'minecraft:light_gray_terracotta'})
			event.remove({id: 'minecraft:cyan_terracotta'})
			event.remove({id: 'minecraft:purple_terracotta'})
			event.remove({id: 'minecraft:blue_terracotta'})
			event.remove({id: 'minecraft:brown_terracotta'})
			event.remove({id: 'minecraft:green_terracotta'})
			event.remove({id: 'minecraft:red_terracotta'})
			event.remove({id: 'minecraft:black_terracotta'})

		// stained_glass by ID
			event.remove({id: 'minecraft:white_stained_glass'})
			event.remove({id: 'minecraft:orange_stained_glass'})
			event.remove({id: 'minecraft:magenta_stained_glass'})
			event.remove({id: 'minecraft:light_blue_stained_glass'})
			event.remove({id: 'minecraft:yellow_stained_glass'})
			event.remove({id: 'minecraft:lime_stained_glass'})
			event.remove({id: 'minecraft:pink_stained_glass'})
			event.remove({id: 'minecraft:gray_stained_glass'})
			event.remove({id: 'minecraft:light_gray_stained_glass'})
			event.remove({id: 'minecraft:cyan_stained_glass'})
			event.remove({id: 'minecraft:purple_stained_glass'})
			event.remove({id: 'minecraft:blue_stained_glass'})
			event.remove({id: 'minecraft:brown_stained_glass'})
			event.remove({id: 'minecraft:green_stained_glass'})
			event.remove({id: 'minecraft:red_stained_glass'})
			event.remove({id: 'minecraft:black_stained_glass'})
			
		// Mossy Output
			event.remove({output: 'minecraft:mossy_cobblestone'})
			event.remove({output: 'minecraft:mossy_cobblestone_slab'})
			event.remove({output: 'minecraft:mossy_cobblestone_stairs'})
			event.remove({output: 'minecraft:mossy_cobblestone_wall'})

		// Mossy Input
			event.remove({input: 'minecraft:mossy_cobblestone'})
			event.remove({input: 'minecraft:mossy_cobblestone_slab'})
			event.remove({input: 'minecraft:mossy_cobblestone_stairs'})
			event.remove({input: 'minecraft:mossy_cobblestone_wall'})



		// Remove Wool Related Vanilla Ids
			event.remove({id: 'minecraft:white_wool_from_string'})
			event.remove({id: 'minecraft:orange_wool'})
			event.remove({id: 'minecraft:magenta_wool'})
			event.remove({id: 'minecraft:light_blue_wool'})
			event.remove({id: 'minecraft:yellow_wool'})
			event.remove({id: 'minecraft:lime_wool'})
			event.remove({id: 'minecraft:pink_wool'})
			event.remove({id: 'minecraft:gray_wool'})
			event.remove({id: 'minecraft:light_gray_wool'})
			event.remove({id: 'minecraft:cyan_wool'})
			event.remove({id: 'minecraft:purple_wool'})
			event.remove({id: 'minecraft:blue_wool'})
			event.remove({id: 'minecraft:brown_wool'})
			event.remove({id: 'minecraft:green_wool'})
			event.remove({id: 'minecraft:red_wool'})
			event.remove({id: 'minecraft:black_wool'})
			event.remove({id: 'minecraft:white_carpet'})
			event.remove({id: 'minecraft:orange_carpet'})
			event.remove({id: 'minecraft:magenta_carpet'})
			event.remove({id: 'minecraft:light_blue_carpet'})
			event.remove({id: 'minecraft:yellow_carpet'})
			event.remove({id: 'minecraft:lime_carpet'})
			event.remove({id: 'minecraft:pink_carpet'})
			event.remove({id: 'minecraft:gray_carpet'})
			event.remove({id: 'minecraft:light_gray_carpet'})
			event.remove({id: 'minecraft:cyan_carpet'})
			event.remove({id: 'minecraft:purple_carpet'})
			event.remove({id: 'minecraft:blue_carpet'})
			event.remove({id: 'minecraft:brown_carpet'})
			event.remove({id: 'minecraft:green_carpet'})
			event.remove({id: 'minecraft:red_carpet'}) 	
			event.remove({id: 'minecraft:black_carpet'}) 			
			event.remove({id: 'minecraft:white_carpet_from_white_carpet'})
			event.remove({id: 'minecraft:orange_carpet_from_white_carpet'})
			event.remove({id: 'minecraft:magenta_carpet_from_white_carpet'})
			event.remove({id: 'minecraft:light_blue_carpet_from_white_carpet'})
			event.remove({id: 'minecraft:yellow_carpet_from_white_carpet'})
			event.remove({id: 'minecraft:lime_carpet_from_white_carpet'})
			event.remove({id: 'minecraft:pink_carpet_from_white_carpet'})
			event.remove({id: 'minecraft:gray_carpet_from_white_carpet'})
			event.remove({id: 'minecraft:light_gray_carpet_from_white_carpet'})
			event.remove({id: 'minecraft:cyan_carpet_from_white_carpet'})
			event.remove({id: 'minecraft:purple_carpet_from_white_carpet'})
			event.remove({id: 'minecraft:blue_carpet_from_white_carpet'})
			event.remove({id: 'minecraft:brown_carpet_from_white_carpet'})
			event.remove({id: 'minecraft:green_carpet_from_white_carpet'})
			event.remove({id: 'minecraft:red_carpet_from_white_carpet'})
			event.remove({id: 'minecraft:black_carpet_from_white_carpet'})
			event.remove({id: 'minecraft:white_banner'})
			event.remove({id: 'minecraft:orange_banner'})
			event.remove({id: 'minecraft:magenta_banner'})
			event.remove({id: 'minecraft:light_blue_banner'})
			event.remove({id: 'minecraft:yellow_banner'})
			event.remove({id: 'minecraft:lime_banner'})
			event.remove({id: 'minecraft:pink_banner'})
			event.remove({id: 'minecraft:gray_banner'})
			event.remove({id: 'minecraft:light_gray_banner'})
			event.remove({id: 'minecraft:cyan_banner'})
			event.remove({id: 'minecraft:purple_banner'})
			event.remove({id: 'minecraft:blue_banner'})
			event.remove({id: 'minecraft:brown_banner'})
			event.remove({id: 'minecraft:green_banner'})
			event.remove({id: 'minecraft:red_banner'}) 	
			event.remove({id: 'minecraft:black_banner'})

		// standstone Output
			event.remove({output: 'minecraft:sandstone'})
			event.remove({output: 'minecraft:chiseled_sandstone'})
			event.remove({output: 'minecraft:cut_sandstone'})
			event.remove({output: 'minecraft:sandstone_slab'})
			event.remove({output: 'minecraft:cut_sandstone_slab'})
			event.remove({output: 'minecraft:red_sandstone_slab'})
			event.remove({output: 'minecraft:cut_red_sandstone_slab'})
			event.remove({output: 'minecraft:smooth_red_sandstone'})
			event.remove({output: 'minecraft:smooth_sandstone'})
			event.remove({output: 'minecraft:sandstone_stairs'})
			event.remove({output: 'minecraft:red_sandstone'})
			event.remove({output: 'minecraft:chiseled_red_sandstone'})
			event.remove({output: 'minecraft:cut_red_sandstone'})
			event.remove({output: 'minecraft:red_sandstone_stairs'})
			event.remove({output: 'minecraft:smooth_red_sandstone'})
			event.remove({output: 'minecraft:smooth_sandstone_stairs'})
			event.remove({output: 'minecraft:smooth_red_sandstone_slab'})
			event.remove({output: 'minecraft:smooth_sandstone_slab'})
			event.remove({output: 'minecraft:red_sandstone_wall'})
			event.remove({output: 'minecraft:sanstone_wall'})

		// Sandstone Input
			event.remove({input: 'minecraft:sandstone'})
			event.remove({input: 'minecraft:chiseled_sandstone'})
			event.remove({input: 'minecraft:cut_sandstone'})
			event.remove({input: 'minecraft:sandstone_slab'})
			event.remove({input: 'minecraft:cut_sandstone_slab'})
			event.remove({input: 'minecraft:red_sandstone_slab'})
			event.remove({input: 'minecraft:cut_red_sandstone_slab'})
			event.remove({input: 'minecraft:smooth_red_sandstone'})
			event.remove({input: 'minecraft:smooth_sandstone'})
			event.remove({input: 'minecraft:sandstone_stairs'})
			event.remove({input: 'minecraft:red_sandstone'})
			event.remove({input: 'minecraft:chiseled_red_sandstone'})
			event.remove({input: 'minecraft:cut_red_sandstone'})
			event.remove({input: 'minecraft:red_sandstone_stairs'})
			event.remove({input: 'minecraft:smooth_red_sandstone'})
			event.remove({input: 'minecraft:smooth_sandstone_stairs'})
			event.remove({input: 'minecraft:smooth_red_sandstone_slab'})
			event.remove({input: 'minecraft:smooth_sandstone_slab'})
			event.remove({input: 'minecraft:red_sandstone_wall'})

		// wood Log Input
			event.remove({input: 'minecraft:oak_log'})
			event.remove({input: 'minecraft:spruce_log'})
			event.remove({input: 'minecraft:birch_log'})
			event.remove({input: 'minecraft:jungle_log'})
			event.remove({input: 'minecraft:acacia_log'})
			event.remove({input: 'minecraft:dark_oak_log'})
			event.remove({input: 'minecraft:mangrove_log'})
			event.remove({input: 'minecraft:crimson_stem'})
			event.remove({input: 'minecraft:warped_stem'})

		// wood slab Input
			event.remove({input: 'minecraft:oak_slab'})
			event.remove({input: 'minecraft:spruce_slab'})
			event.remove({input: 'minecraft:birch_slab'})
			event.remove({input: 'minecraft:jungle_slab'})
			event.remove({input: 'minecraft:acacia_slab'})
			event.remove({input: 'minecraft:dark_oak_slab'})
			event.remove({input: 'minecraft:mangrove_slab'})
			event.remove({input: 'minecraft:crimson_slab'})
			event.remove({input: 'minecraft:warped_slab'})

		//  slab Input
			event.remove({input: 'minecraft:stone_slab'})
			event.remove({input: 'minecraft:smooth_stone_slab'})
			event.remove({input: 'minecraft:petrified_oak_slab'})
			event.remove({input: 'minecraft:cobblestone_slab'})
			event.remove({input: 'minecraft:stone_brick_slab'})
			event.remove({input: 'minecraft:mud_brick_slab'})
			event.remove({input: 'minecraft:nether_brick_slab'})
			event.remove({input: 'minecraft:primsmarine_slab'})
			event.remove({input: 'minecraft:prismarine_brick_slab'})
			event.remove({input: 'minecraft:dark_prismarine_slab'})

		//  slab Output
			event.remove({output: 'minecraft:stone_slab'})
			event.remove({output: 'minecraft:smooth_stone_slab'})
			event.remove({output: 'minecraft:pertrified_oak_slab'})
			event.remove({output: 'minecraft:cobblestone_slab'})
			event.remove({output: 'minecraft:stone_brick_slab'})
			event.remove({output: 'minecraft:mud_brick_slab'})
			event.remove({output: 'minecraft:nether_brick_slab'})
			event.remove({output: 'minecraft:primsmarine_slab'})
			event.remove({output: 'minecraft:prismarine_brick_slab'})
			event.remove({output: 'minecraft:dark_prismarine_slab'})

			
		// Remove By Id ( Copper since Mojang ADDED SO FUCKING MUCH )
			event.remove({input: 'minecraft:honeycomb'})
			event.remove({id: 'minecraft:cut_copper'})
			event.remove({id: 'minecraft:exposed_cut_copper'})
			event.remove({id: 'minecraft:weathered_cut_copper'})
			event.remove({id: 'minecraft:oxidized_cut_copper'})
			event.remove({id: 'minecraft:cut_copper_slab'})
			event.remove({id: 'minecraft:cut_copper_stairs'})
			event.remove({id: 'minecraft:exposed_cut_copper_slab'})
			event.remove({id: 'minecraft:exposed_cut_copper_stairs'})
			event.remove({id: 'minecraft:weathered_cut_copper_stairs'})
			event.remove({id: 'minecraft:weathered_cut_copper_slab'})
			event.remove({id: 'minecraft:oxidized_cut_copper_slab'})
			event.remove({id: 'minecraft:oxidized_cut_copper_stairs'})
			event.remove({id: 'minecraft:waxed_cut_copper'})
			event.remove({id: 'minecraft:waxed_exposed_cut_copper'})
			event.remove({id: 'minecraft:waxed_weathered_cut_copper'})
			event.remove({id: 'minecraft:waxed_oxidized_copper'})
			event.remove({id: 'minecraft:waxed_cut_copper_slab'})
			event.remove({id: 'minecraft:waxed_cut_copper_stairs'})
			event.remove({id: 'minecraft:waxed_exposed_cut_copper_stairs'})
			event.remove({id: 'minecraft:waxed_exposed_cut_copper_slab'})
			event.remove({id: 'minecraft:waxed_weathered_cut_copper_slab'})
			event.remove({id: 'minecraft:waxed_weathered_cut_copper_stairs'})
			event.remove({id: 'minecraft:waxed_oxidized_cut_copper_stairs'})
			event.remove({id: 'minecraft:waxed_oxidized_cut_copper_slab'})

		// Metal Output
			event.remove({output: 'minecraft:netherite_block'})
		
		// rawOutput
			event.remove({output: 'minecraft:raw_iron_block'})
			event.remove({output: 'minecraft:raw_copper_block'})
			event.remove({output: 'minecraft:raw_gold_block'})
			event.remove({output: 'minecraft:budding_amethyst'})

		// rawInput
			event.remove({input: 'minecraft:raw_iron_block'})
			event.remove({input: 'minecraft:raw_copper_block'})
			event.remove({input: 'minecraft:raw_gold_block'})
			event.remove({input: 'minecraft:budding_amethyst'})
	
		// oreOutput
			event.remove({output: 'minecraft:coal_ore'})
			event.remove({output: 'minecraft:iron_ore'})
			event.remove({output: 'minecraft:copper_ore'})
			event.remove({output: 'minecraft:gold_ore'})
			event.remove({output: 'minecraft:redstone_ore'})
			event.remove({output: 'minecraft:emerald_ore'})
			event.remove({output: 'minecraft:lapis_ore'})
			event.remove({output: 'minecraft:diamond_ore'})
			event.remove({output: 'minecraft:nether_gold_ore'})
			event.remove({output: 'minecraft:nether_quartz_ore'})
	
		// oreInput
			event.remove({input: 'minecraft:coal_ore'})
			event.remove({input: 'minecraft:iron_ore'})
			event.remove({input: 'minecraft:copper_ore'})
			event.remove({input: 'minecraft:gold_ore'})
			event.remove({input: 'minecraft:redstone_ore'})
			event.remove({input: 'minecraft:emerald_ore'})
			event.remove({input: 'minecraft:lapis_ore'})
			event.remove({input: 'minecraft:diamond_ore'})
			event.remove({input: 'minecraft:nether_gold_ore'})
			event.remove({input: 'minecraft:nether_quartz_ore'})
	
		// woodOutput
			event.remove({output: 'minecraft:oak_planks'})
			event.remove({output: 'minecraft:spruce_planks'})
			event.remove({output: 'minecraft:birch_planks'})
			event.remove({output: 'minecraft:jungle_planks'})
			event.remove({output: 'minecraft:acacia_planks'})
			event.remove({output: 'minecraft:dark_oak_planks'})
			event.remove({output: 'minecraft:mangrove_planks'})
			event.remove({output: 'minecraft:crimson_planks'})
			event.remove({output: 'minecraft:warmped_planks'})
			event.remove({output: 'minecraft:stripped_oak_log'})
			event.remove({output: 'minecraft:stripped_spruce_log'})
			event.remove({output: 'minecraft:stripped_birch_log'})
			event.remove({output: 'minecraft:stripped_jungle_log'})
			event.remove({output: 'minecraft:stripped_acacia_log'})
			event.remove({output: 'minecraft:stripped_dark_oak_log'})
			event.remove({output: 'minecraft:stripped_mangrove_log'})
			event.remove({output: 'minecraft:stripped_warped_step'})
			event.remove({output: 'minecraft:stripped_crimson_stem'})
	
		// woodInput
			event.remove({input: 'minecraft:oak_planks'})
			event.remove({input: 'minecraft:spruce_planks'})
			event.remove({input: 'minecraft:birch_planks'})
			event.remove({input: 'minecraft:jungle_planks'})
			event.remove({input: 'minecraft:acacia_planks'})
			event.remove({input: 'minecraft:dark_oak_planks'})
			event.remove({input: 'minecraft:mangrove_planks'})
			event.remove({input: 'minecraft:crimson_planks'})
			event.remove({input: 'minecraft:warmped_planks'})
			event.remove({input: 'minecraft:stripped_oak_log'})
			event.remove({input: 'minecraft:stripped_spruce_log'})
			event.remove({input: 'minecraft:stripped_birch_log'})
			event.remove({input: 'minecraft:stripped_jungle_log'})
			event.remove({input: 'minecraft:stripped_acacia_log'})
			event.remove({input: 'minecraft:stripped_dark_oak_log'})
			event.remove({input: 'minecraft:stripped_mangrove_log'})
			event.remove({input: 'minecraft:stripped_warped_step'})
			event.remove({input: 'minecraft:stripped_crimson_stem'})

		// Gem Output
			event.remove({output: 'minecraft:amethyst_block'})
			event.remove({output: 'minecraft:diamond_block'})

		// Gem input
			event.remove({input: 'minecraft:amethyst_shard'})
	
	
		// stoneMisc
			event.remove({output: 'minecraft:bedrock'})
			
		// sand Output
			event.remove({output: 'minecraft:sand'})
			event.remove({output: 'minecraft:red_sand'})

		// sand Input
			event.remove({input: 'minecraft:sand'})
			event.remove({input: 'minecraft:red_sand'})
	
		// granite Output
			event.remove({output: 'minecraft:granite'})
			event.remove({output: 'minecraft:polished_granite'})
	
		// granite Input
			event.remove({input: 'minecraft:granite'})
			event.remove({input: 'minecraft:polished_granite'})
	
		// diorite Output
			event.remove({output: 'minecraft:diorite'})
			event.remove({output: 'minecraft:polished_diorite'})	
		
		// diorite Input
			event.remove({input: 'minecraft:diorite'})
			event.remove({input: 'minecraft:polished_diorite'})
	
		// andesite Output
			event.remove({output: 'minecraft:andesite'})
			event.remove({output: 'minecraft:polished_andesite'})
		
		// andesite Input
			event.remove({input: 'minecraft:andesite'})
			event.remove({input: 'minecraft:polished_andesite'})
	
		// calcite Output
			event.remove({output: 'minecraft:calcite'})

		// calcite Input
			event.remove({input: 'minecraft:calcite'})
	
		// tuff Output
			event.remove({output: 'minecraft:tuff'})
	
		// tuff Input
			event.remove({input: 'minecraft:tuff'})
	
		// stone Output
			event.remove({output: 'minecraft:cobblestone'})
			event.remove({output: 'minecraft:stone'})
			event.remove({output: 'minecraft:gravel'})

		// stone Input
			event.remove({input: 'minecraft:cobblestone'})
			event.remove({input: 'minecraft:stone'})
			event.remove({input: 'minecraft:gravel'})
	
		// Grass/Dirt Output
			event.remove({output: 'minecraft:grass_block'})
			event.remove({output: 'minecraft:dirt'})
			event.remove({output: 'minecraft:coarse_dirt'})
			event.remove({output: 'minecraft:podzol'})
			event.remove({output: 'minecraft:rooted_dirt'})
			event.remove({output: 'minecraft:mud'})
			event.remove({output: 'minecraft:crimson_nylium'})
			event.remove({output: 'minecraft:warped_nylium'})

		// Grass/Dirt Input
			event.remove({input: 'minecraft:grass_block'})
			event.remove({input: 'minecraft:dirt'})
			event.remove({input: 'minecraft:coarse_dirt'})
			event.remove({input: 'minecraft:podzol'})
			event.remove({input: 'minecraft:rooted_dirt'})
			event.remove({input: 'minecraft:mud'})
			event.remove({input: 'minecraft:crimson_nylium'})
			event.remove({input: 'minecraft:warped_nylium'})

		//Crimson Planks Output
			event.remove({output: 'minecraft:crimson_planks'})
			
		//Crimson Planks Input
			event.remove({input: 'minecraft:crimson_planks'})
		
		//Warped Planks Output
			event.remove({output: 'minecraft:warped_planks'})

		//Warped Planks Input
			event.remove({input: 'minecraft:warped_planks'})

		// dripstone Output
			event.remove({output: 'minecraft:dripstone_block'})
			event.remove({output: 'minecraft:pointed_dripstone'})
			event.remove({output: 'minecraft:cut_dripstone'})
			event.remove({output: 'minecraft:cut_dripstone_stairs'})
			event.remove({output: 'minecraft:cut_dripstone_slab'})
			event.remove({output: 'minecraft:cut_dripstone_wall'})
			event.remove({output: 'minecraft:polished_cut_dripstone'})
			event.remove({output: 'minecraft:polished_cut_dripstone_stairs'})
			event.remove({output: 'minecraft:polished_cut_dripstone_slab'})
			event.remove({output: 'minecraft:polished_cut_dripstone_wall'})
			event.remove({output: 'minecraft:polished_cut_dripstone_'})
			event.remove({output: 'minecraft:cut_dripstone_bricks'})
			event.remove({output: 'minecraft:cut_dripstone_stairs'})
			event.remove({output: 'minecraft:cut_dripstone_slab'})
			event.remove({output: 'minecraft:cut_dripstone_wall'})
			event.remove({output: 'minecraft:small_dripstone_bricks'})
			event.remove({output: 'minecraft:small_dripstone_stairs'})
			event.remove({output: 'minecraft:small_dripstone_slab'})
			event.remove({output: 'minecraft:small_dripstone_wall'})
		
		// dripstone Input
			event.remove({input: 'minecraft:dripstone_block'})
			event.remove({input: 'minecraft:pointed_dripstone'})
			event.remove({input: 'minecraft:cut_dripstone'})
			event.remove({input: 'minecraft:cut_dripstone_stairs'})
			event.remove({input: 'minecraft:cut_dripstone_slab'})
			event.remove({input: 'minecraft:cut_dripstone_wall'})
			event.remove({input: 'minecraft:polished_cut_dripstone'})
			event.remove({input: 'minecraft:polished_cut_dripstone_stairs'})
			event.remove({input: 'minecraft:polished_cut_dripstone_slab'})
			event.remove({input: 'minecraft:polished_cut_dripstone_wall'})
			event.remove({input: 'minecraft:polished_cut_dripstone_'})
			event.remove({input: 'minecraft:cut_dripstone_bricks'})
			event.remove({input: 'minecraft:cut_dripstone_stairs'})
			event.remove({input: 'minecraft:cut_dripstone_slab'})
			event.remove({input: 'minecraft:cut_dripstone_wall'})
			event.remove({input: 'minecraft:small_dripstone_bricks'})
			event.remove({input: 'minecraft:small_dripstone_stairs'})
			event.remove({input: 'minecraft:small_dripstone_slab'})
			event.remove({input: 'minecraft:small_dripstone_wall'})

		// Deepslate Output
			event.remove({output: 'minecraft:deepslate'})
			event.remove({output: 'minecraft:cobbled_deepslate'})
			event.remove({output: 'minecraft:polished_deepslate'})
			event.remove({output: 'minecraft:deepslate_coal_ore'})
			event.remove({output: 'minecraft:deepslate_iron_ore'})
			event.remove({output: 'minecraft:deepslate_copper_ore'})
			event.remove({output: 'minecraft:deepslate_gold_ore'})
			event.remove({output: 'minecraft:deepslate_redstone_ore'})
			event.remove({output: 'minecraft:deepslate_emerald_ore'})
			event.remove({output: 'minecraft:deepslate_lapis_ore'})
			event.remove({output: 'minecraft:deepslate_diamond_ore'})
			event.remove({output: 'minecraft:deepslate_bricks'})
			event.remove({output: 'minecraft:cracked_deepslate_bricks'})
			event.remove({output: 'minecraft:deepslate_tiles'})
			event.remove({output: 'minecraft:cracked_deepslate_tiles'})
			event.remove({output: 'minecraft:chiseled_deepslate'})
			event.remove({output: 'minecraft:reinforced_deepslate'})
			event.remove({output: 'minecraft:cobble_deepslate_stairs'})
			event.remove({output: 'minecraft:polished_deepslate_stairs'})
			event.remove({output: 'minecraft:deepslate_brick_stairs'})
			event.remove({output: 'minecraft:deepslate_tile_stairs'})
			event.remove({output: 'minecraft:cobble_deepslate_slab'})
			event.remove({output: 'minecraft:polished_deepslate_slab'})
			event.remove({output: 'minecraft:deepslate_brick_slab'})
			event.remove({output: 'minecraft:deepslate_tile_slab'})
			event.remove({output: 'minecraft:infested_deepslate'})
			event.remove({output: 'minecraft:cobble_deepslate_wall'})
			event.remove({output: 'minecraft:polished_deepslate_wall'})
			event.remove({output: 'minecraft:deepslate_brick_wall'})
			event.remove({output: 'minecraft:deepslate_tile_wall'})
			event.remove({output: 'minecraft:deepslate_zinc_ore'})

		// Deepslate Input
			event.remove({input: 'minecraft:deepslate'})
			event.remove({input: 'minecraft:cobbled_deepslate'})
			event.remove({input: 'minecraft:polished_deepslate'})
			event.remove({input: 'minecraft:deepslate_coal_ore'})
			event.remove({input: 'minecraft:deepslate_iron_ore'})
			event.remove({input: 'minecraft:deepslate_copper_ore'})
			event.remove({input: 'minecraft:deepslate_gold_ore'})
			event.remove({input: 'minecraft:deepslate_redstone_ore'})
			event.remove({input: 'minecraft:deepslate_emerald_ore'})
			event.remove({input: 'minecraft:deepslate_lapis_ore'})
			event.remove({input: 'minecraft:deepslate_diamond_ore'})
			event.remove({input: 'minecraft:deepslate_bricks'})
			event.remove({input: 'minecraft:cracked_deepslate_bricks'})
			event.remove({input: 'minecraft:deepslate_tiles'})
			event.remove({input: 'minecraft:cracked_deepslate_tiles'})
			event.remove({input: 'minecraft:chiseled_deepslate'})
			event.remove({input: 'minecraft:reinforced_deepslate'})
			event.remove({input: 'minecraft:cobble_deepslate_stairs'})
			event.remove({input: 'minecraft:polished_deepslate_stairs'})
			event.remove({input: 'minecraft:deepslate_brick_stairs'})
			event.remove({input: 'minecraft:deepslate_tile_stairs'})
			event.remove({input: 'minecraft:cobble_deepslate_slab'})
			event.remove({input: 'minecraft:polished_deepslate_slab'})
			event.remove({input: 'minecraft:deepslate_brick_slab'})
			event.remove({input: 'minecraft:deepslate_tile_slab'})
			event.remove({input: 'minecraft:infested_deepslate'})
			event.remove({input: 'minecraft:cobble_deepslate_wall'})
			event.remove({input: 'minecraft:polished_deepslate_wall'})
			event.remove({input: 'minecraft:deepslate_brick_wall'})
			event.remove({input: 'minecraft:deepslate_tile_wall'})
			event.remove({input: 'minecraft:deepslate_zinc_ore'})

		// blackstone Output
			event.remove({output: 'minecraft:blackstone'})
			event.remove({output: 'minecraft:blackstone_slab'})
			event.remove({output: 'minecraft:blackstone_stairs'})
			event.remove({output: 'minecraft:gilded_blackstone'})
			event.remove({output: 'minecraft:polished_blackstone'})
			event.remove({output: 'minecraft:polished_blackstone_slab'})
			event.remove({output: 'minecraft:polished_blackstone_stairs'})
			event.remove({output: 'minecraft:chiseled_polished_blackstone'})
			event.remove({output: 'minecraft:polished_blackstone_bricks'})
			event.remove({output: 'minecraft:polished_blackstone_brick_slab'})
			event.remove({output: 'minecraft:polished_blackstone_brick_stairs'})
			event.remove({output: 'minecraft:cracked_polished_blackstone_bricks'})
		
		// blackstone Input
			event.remove({input: 'minecraft:blackstone'})
			event.remove({input: 'minecraft:blackstone_slab'})
			event.remove({input: 'minecraft:blackstone_stairs'})
			event.remove({input: 'minecraft:gilded_blackstone'})
			event.remove({input: 'minecraft:polished_blackstone'})
			event.remove({input: 'minecraft:polished_blackstone_slab'})
			event.remove({input: 'minecraft:polished_blackstone_stairs'})
			event.remove({input: 'minecraft:chiseled_polished_blackstone'})
			event.remove({input: 'minecraft:polished_blackstone_bricks'})
			event.remove({input: 'minecraft:polished_blackstone_brick_slab'})
			event.remove({input: 'minecraft:polished_blackstone_brick_stairs'})
			event.remove({input: 'minecraft:cracked_polished_blackstone_bricks'})
		
		// Flowers Output
			event.remove({output: 'minecraft:dandelion'})
			event.remove({output: 'minecraft:poppy'})
			event.remove({output: 'minecraft:blue_orchid'})
			event.remove({output: 'minecraft:allium'})
			event.remove({output: 'minecraft:azure_bluet'})
			event.remove({output: 'minecraft:red_tulip'})
			event.remove({output: 'minecraft:orange_tulip'})
			event.remove({output: 'minecraft:white_tulip'})
			event.remove({output: 'minecraft:pink_tulip'})
			event.remove({output: 'minecraft:oxeye_daisy'})
			event.remove({output: 'minecraft:cornflower'})
			event.remove({output: 'minecraft:lily_of_the_valley'})
			event.remove({output: 'minecraft:wither_rose'})
			event.remove({output: 'minecraft:spore_blossom'})
			event.remove({output: 'minecraft:brown_mushroom'})
			event.remove({output: 'minecraft:red_mushroom'})
			event.remove({output: 'minecraft:crimson_fungus'})
			event.remove({output: 'minecraft:warped_fungus'})
			event.remove({output: 'minecraft:crimson_roots'})
			event.remove({output: 'minecraft:warped_roots'})
			event.remove({output: 'minecraft:nether_sprouts'})
			event.remove({output: 'minecraft:weeping_vines'})
			event.remove({output: 'minecraft:twisting_vines'})

		// Flowers Input			
		    event.remove({input: 'minecraft:dandelion'})
			event.remove({input: 'minecraft:poppy'})
			event.remove({input: 'minecraft:blue_orchid'})
			event.remove({input: 'minecraft:allium'})
			event.remove({input: 'minecraft:azure_bluet'})
			event.remove({input: 'minecraft:red_tulip'})
			event.remove({input: 'minecraft:orange_tulip'})
			event.remove({input: 'minecraft:white_tulip'})
			event.remove({input: 'minecraft:pink_tulip'})
			event.remove({input: 'minecraft:oxeye_daisy'})
			event.remove({input: 'minecraft:cornflower'})
			event.remove({input: 'minecraft:lily_of_the_valley'})
			event.remove({input: 'minecraft:wither_rose'})
			event.remove({input: 'minecraft:spore_blossom'})
			event.remove({input: 'minecraft:brown_mushroom'})
			event.remove({input: 'minecraft:red_mushroom'})
			event.remove({input: 'minecraft:crimson_fungus'})
			event.remove({input: 'minecraft:warped_fungus'})
			event.remove({input: 'minecraft:crimson_roots'})
			event.remove({input: 'minecraft:warped_roots'})
			event.remove({input: 'minecraft:nether_sprouts'})
			event.remove({input: 'minecraft:weeping_vines'})
			event.remove({input: 'minecraft:twisting_vines'})
			event.remove({input: 'minecraft:sugar_cane'})
			event.remove({input: 'minecraft:sunflower'})
	
	})