// priority: 0

console.info('Hello, World! (You will only see this line once in console, during startup)')

StartupEvents.registry('item', event => {


event.create('double_ingot_aluminium').displayName('aluminium Double Ingot').texture("kubejs:item/metal/double_ingot").color(0, 0x69A4C4)
event.create('double_ingot_americium').displayName('americium Double Ingot').texture("kubejs:item/metal/double_ingot").color(0, 0x18483F)
event.create('double_ingot_annealed_copper').displayName('Annealed Copper Double Ingot').texture("kubejs:item/metal/double_ingot").color(0, 0xB9662B)
event.create('double_ingot_antimony').displayName('Antimony Double Ingot').texture("kubejs:item/metal/double_ingot").color(0, 0x9898A6)
event.create('double_ingot_battery_alloy').displayName('Battery Alloy Double Ingot').texture("kubejs:item/metal/double_ingot").color(0, 0x745C77)
event.create('double_ingot_beryllium').displayName('Beryllium Double Ingot').texture("kubejs:item/metal/double_ingot").color(0, 0x5BA45B)
event.create('double_ingot_bismuth').displayName('Bismuth Double Ingot').texture("kubejs:item/metal/double_ingot").color(0, 0x284141)
event.create('double_ingot_bismuth_bronze').displayName('Bismuth Bronze Double Ingot').texture("kubejs:item/metal/double_ingot").color(0, 0x293333)
event.create('double_ingot_black_bronze').displayName('Black Bronze Double Ingot').texture("kubejs:item/metal/double_ingot").color(0, 0x201028)
event.create('double_ingot_black_steel').displayName('Black Steel Double Ingot').texture("kubejs:item/metal/double_ingot").color(0, 0x282828)
event.create('double_ingot_blue_alloy').displayName('Blue Alloy Double Ingot').texture("kubejs:item/metal/double_ingot").color(0, 0x24405B)
event.create('double_ingot_blue_steel').displayName('Blue Steel Double Ingot').texture("kubejs:item/metal/double_ingot").color(0, 0x222230)
event.create('double_ingot_borosilicate_glass').displayName('Borosilicate Glass Double Ingot').texture("kubejs:item/metal/double_ingot").color(0, 0x505450)
event.create('double_ingot_brass').displayName('Brass Double Ingot').texture("kubejs:item/metal/double_ingot").color(0, 0x5C4100)
event.create('double_ingot_bronze').displayName('Bronze Double Ingot').texture("kubejs:item/metal/double_ingot").color(0, 0xB35A00)
event.create('double_ingot_chrome').displayName('Chrome Double Ingot').texture("kubejs:item/metal/double_ingot").color(0, 0xA48997)
event.create('double_ingot_cobalt').displayName('Cobalt Double Ingot').texture("kubejs:item/metal/double_ingot").color(0, 0x3535A6)
event.create('double_ingot_cobalt_brass').displayName('Cobalt Brass Double Ingot').texture("kubejs:item/metal/double_ingot").color(0, 0x78786B)
event.create('double_ingot_copper').displayName('Copper Double Ingot').texture("kubejs:item/metal/double_ingot").color(0, 0xB9662B)
event.create('double_ingot_cupronickel').displayName('Cupronickel Double Ingot').texture("kubejs:item/metal/double_ingot").color(0, 0x986456)
event.create('double_ingot_damascus_steel').displayName('Damascus Steel Double Ingot').texture("kubejs:item/metal/double_ingot").color(0, 0x484848)
event.create('double_ingot_darmstadtium').displayName('Darmstadtium Double Ingot').texture("kubejs:item/metal/double_ingot").color(0, 0x3C5844)
event.create('double_ingot_duranium').displayName('Duranium Double Ingot').texture("kubejs:item/metal/double_ingot").color(0, 0x327474)
event.create('double_ingot_electrum').displayName('Electum Double Ingot').texture("kubejs:item/metal/double_ingot").color(0, 0xBBBB49)
event.create('double_ingot_enriched_naquadah_trinium_europium_duranide').displayName('Enriched Naquadah Trinium Europium Duranide Double Ingot').texture("kubejs:item/metal/double_ingot").color(0, 0x4B5A45)
event.create('double_ingot_epoxy').displayName('Epoxy Double Ingot').texture("kubejs:item/metal/double_ingot").color(0, 0x865E0D)
event.create('double_ingot_europium').displayName('Europium Double Ingot').texture("kubejs:item/metal/double_ingot").color(0, 0x15A9A9)
event.create('double_ingot_gallium').displayName('Gallium Double Ingot').texture("kubejs:item/metal/double_ingot").color(0, 0x9797AF)
event.create('double_ingot_gallium_arsenide').displayName('Gallium Arsenide Double Ingot').texture("kubejs:item/metal/double_ingot").color(0, 0x676767)
event.create('double_ingot_hsse').displayName('Hsse Double Ingot').texture("kubejs:item/metal/double_ingot").color(0, 0x214200)
event.create('double_ingot_hssg').displayName('Hssg Double Ingot').texture("kubejs:item/metal/double_ingot").color(0, 0x636300)
event.create('double_ingot_hsss').displayName('Hsss Double Ingot').texture("kubejs:item/metal/double_ingot").color(0, 0x470023)
event.create('double_ingot_indium').displayName('Indium Double Ingot').texture("kubejs:item/metal/double_ingot").color(0, 0x6B6A66)
event.create('double_ingot_indium_gallium_phosphide').displayName('Gallium Phosphide Double Ingot').texture("kubejs:item/metal/double_ingot").color(0, 0x6A5D7E)
event.create('double_ingot_indium_tin_barium_titanium_cuprate').displayName('Indium Tin Barium Titanium Cuprate Double Ingot').texture("kubejs:item/metal/double_ingot").color(0, 0x5D2E00)
event.create('double_ingot_invar').displayName('Invar Double Ingot').texture("kubejs:item/metal/double_ingot").color(0, 0x7E7E54)
event.create('double_ingot_iridium').displayName('Iridium Double Ingot').texture("kubejs:item/metal/double_ingot").color(0, 0x5B8080)
event.create('double_ingot_iron_magnetic').displayName('Iron Magnetic Double Ingot').texture("kubejs:item/metal/double_ingot").color(0, 0x7E7E7E)
event.create('double_ingot_kanthal').displayName('Kanthal Double Ingot').texture("kubejs:item/metal/double_ingot").color(0, 0x7B858E)
event.create('double_ingot_lead').displayName('Lead Double Ingot').texture("kubejs:item/metal/double_ingot").color(0, 0x583F58)
event.create('double_ingot_magnalium').displayName('Magnalium Double Ingot').texture("kubejs:item/metal/double_ingot").color(0, 0x7D779F)
event.create('double_ingot_magnesium_diboride').displayName('Magnesium Diboride Double Ingot').texture("kubejs:item/metal/double_ingot").color(0, 0x201000)
event.create('double_ingot_manganese').displayName('Manganese Double Ingot').texture("kubejs:item/metal/double_ingot").color(0, 0x869379)
event.create('double_ingot_manganese_phosphide').displayName('Manganese Phosphide Double Ingot').texture("kubejs:item/metal/double_ingot").color(0, 0xAD8B41)
event.create('double_ingot_mercury_barium_calcium_cuprate').displayName('Mercury Barium Calcium Cuprate Double Ingot').texture("kubejs:item/metal/double_ingot").color(0, 0x3B3B3B)
event.create('double_ingot_molybdenum').displayName('Molybdenum Double Ingot').texture("kubejs:item/metal/double_ingot").color(0, 0x7C7C97)
event.create('double_ingot_naquadah').displayName('Naquadah Double Ingot').texture("kubejs:item/metal/double_ingot").color(0, 0x212121)
event.create('double_ingot_naquadah_alloy').displayName('Naquadah Alloy Double Ingot').texture("kubejs:item/metal/double_ingot").color(0, 0x1A1A1A)
event.create('double_ingot_naquadah_enriched').displayName('Naquadah Enriched Double Ingot').texture("kubejs:item/metal/double_ingot").color(0, 0x262626)
event.create('double_ingot_naquadria').displayName('Naquadria Double Ingot').texture("kubejs:item/metal/double_ingot").color(0, 0x141414)
event.create('double_ingot_neodymium').displayName('Neodymium Double Ingot').texture("kubejs:item/metal/double_ingot").color(0, 0x464646)
event.create('double_ingot_neodymium_magnetic').displayName('Neodymium Magnetic Double Ingot').texture("kubejs:item/metal/double_ingot").color(0, 0x404040)
event.create('double_ingot_neutronium').displayName('Neutronium Double Ingot').texture("kubejs:item/metal/double_ingot").color(0, 0x9D9D9D)
event.create('double_ingot_nichrome').displayName('Nichrome Double Ingot').texture("kubejs:item/metal/double_ingot").color(0, 0x8687A1)
event.create('double_ingot_nickel').displayName('Nickel Double Ingot').texture("kubejs:item/metal/double_ingot").color(0, 0x7E7E9E)
event.create('double_ingot_nickel_zinc_ferrite').displayName('Nickel Zinc Ferrite Double Ingot').texture("kubejs:item/metal/double_ingot").color(0, 0x2B2B2B)
event.create('double_ingot_niobium').displayName('Niobium Double Ingot').texture("kubejs:item/metal/double_ingot").color(0, 0x171717)
event.create('double_ingot_niobium_nitride').displayName('Niobium Nitride Double Ingot').texture("kubejs:item/metal/double_ingot").color(0, 0x121912)
event.create('double_ingot_niobium_titanium').displayName('Niobium Titanium Double Ingot').texture("kubejs:item/metal/double_ingot").color(0, 0x121219)
event.create('double_ingot_osmiridium').displayName('Osmiridium Double Ingot').texture("kubejs:item/metal/double_ingot").color(0, 0x4848B7)
event.create('double_ingot_osmium').displayName('Osmium Double Ingot').texture("kubejs:item/metal/double_ingot").color(0, 0x1C1C8F)
event.create('double_ingot_palladium').displayName('Palladium Double Ingot').texture("kubejs:item/metal/double_ingot").color(0, 0x555555)
event.create('double_ingot_plastic').displayName('Plastic Double Ingot').texture("kubejs:item/metal/double_ingot").color(0, 0x888888)
event.create('double_ingot_platinum').displayName('Platinum Double Ingot').texture("kubejs:item/metal/double_ingot").color(0, 0xB1B18B)
event.create('double_ingot_plutonium').displayName('Plutonium Double Ingot').texture("kubejs:item/metal/double_ingot").color(0, 0x9D2121)
event.create('double_ingot_plutonium_241').displayName('Plutonium_241 Double Ingot').texture("kubejs:item/metal/double_ingot").color(0, 0xA32E2E)
event.create('double_ingot_polybenzimidazole').displayName('Polybenzimidazole Double Ingot').texture("kubejs:item/metal/double_ingot").color(0, 0x1E1E1E)
event.create('double_ingot_polycaprolactam').displayName('Polycaprolactam Double Ingot').texture("kubejs:item/metal/double_ingot").color(0, 0x1C1C1C)
event.create('double_ingot_polyphenylene_sulfide').displayName('Polyphenylene Sulfide Double Ingot').texture("kubejs:item/metal/double_ingot").color(0, 0x6F5900)
event.create('double_ingot_polytetrafluoroethylene').displayName('Polytetrafluoroethylene Double Ingot').texture("kubejs:item/metal/double_ingot").color(0, 0x464646)
event.create('double_ingot_polyvinyl_butyral').displayName('Polyvinyl Butyral Double Ingot').texture("kubejs:item/metal/double_ingot").color(0, 0x286032)
event.create('double_ingot_polyvinyl_chloride').displayName('Polyvinyl Chloride Double Ingot').texture("kubejs:item/metal/double_ingot").color(0, 0x919B9B)
event.create('double_ingot_potin').displayName('Potin Double Ingot').texture("kubejs:item/metal/double_ingot").color(0, 0x6F5347)
event.create('double_ingot_red_alloy').displayName('Red Alloy Double Ingot').texture("kubejs:item/metal/double_ingot").color(0, 0x8B0000)
event.create('double_ingot_red_steel').displayName('Red Steel Double Ingot').texture("kubejs:item/metal/double_ingot").color(0, 0x5E4343)
event.create('double_ingot_reinforced_epoxy_resin').displayName('Reinforced Epoxy Resin Double Ingot').texture("kubejs:item/metal/double_ingot").color(0, 0x644D0A)
event.create('double_ingot_rhodium').displayName('Rhodium Double Ingot').texture("kubejs:item/metal/double_ingot").color(0, 0x94083B)
event.create('double_ingot_rhodium_plated_palladium').displayName('Rhodium Plated Palladium Double Ingot').texture("kubejs:item/metal/double_ingot").color(0, 0x8F8181)
event.create('double_ingot_rose_gold').displayName('Rose Gold Double Ingot').texture("kubejs:item/metal/double_ingot").color(0, 0xB3A115)
event.create('double_ingot_rubber').displayName('Rubber Double Ingot').texture("kubejs:item/metal/double_ingot").color(0, 0x000000)
event.create('double_ingot_ruridit').displayName('Ruridit Double Ingot').texture("kubejs:item/metal/double_ingot").color(0, 0x4A8559)
event.create('double_ingot_ruthenium').displayName('Ruthenium Double Ingot').texture("kubejs:item/metal/double_ingot").color(0, 0x36748A)
event.create('double_ingot_ruthenium_trinium_americium_neutronate').displayName('Ruthenium Trinium Americium Neutronate Double Ingot').texture("kubejs:item/metal/double_ingot").color(0, 0xB2B2B2)
event.create('double_ingot_samarium').displayName('Samarium Double Ingot').texture("kubejs:item/metal/double_ingot").color(0, 0xB0B08D)
event.create('double_ingot_samarium_iron_arsenic_oxide').displayName('Samarium Iron Arsenic Oxide Double Ingot').texture("kubejs:item/metal/double_ingot").color(0, 0x240024)
event.create('double_ingot_samarium_magnetic').displayName('Samarium Magnetic Double Ingot').texture("kubejs:item/metal/double_ingot").color(0, 0xA4A484)
event.create('double_ingot_silicon').displayName('Silicon Double Ingot').texture("kubejs:item/metal/double_ingot").color(0, 0x21212C)
event.create('double_ingot_silicone_rubber').displayName('Silicone Rubber Double Ingot').texture("kubejs:item/metal/double_ingot").color(0, 0x898989)
event.create('double_ingot_silver').displayName('Silver Double Ingot').texture("kubejs:item/metal/double_ingot").color(0, 0x9494AB)
event.create('double_ingot_soldering_alloy').displayName('Soldering Alloy Double Ingot').texture("kubejs:item/metal/double_ingot").color(0, 0x696970)
event.create('double_ingot_stainless_steel').displayName('Stainless Steel Double Ingot').texture("kubejs:item/metal/double_ingot").color(0, 0x868694)
event.create('double_ingot_steel').displayName('Steel Double Ingot').texture("kubejs:item/metal/double_ingot").color(0, 0x555555)
event.create('double_ingot_steel_magnetic').displayName('Steel Magnetic Double Ingot').texture("kubejs:item/metal/double_ingot").color(0, 0x474747)
event.create('double_ingot_sterling_silver').displayName('Sterling Silver Double Ingot').texture("kubejs:item/metal/double_ingot").color(0, 0xAF9A9E)
event.create('double_ingot_styrene_butadiene_rubber').displayName('Styrene Butadiene Rubber Double Ingot').texture("kubejs:item/metal/double_ingot").color(0, 0x151110)
event.create('double_ingot_tantalum').displayName('Tantalum Double Ingot').texture("kubejs:item/metal/double_ingot").color(0, 0x4F4F5D)
event.create('double_ingot_thorium').displayName('Thorium Double Ingot').texture("kubejs:item/metal/double_ingot").color(0, 0x001400)
event.create('double_ingot_tin').displayName('Tin Double Ingot').texture("kubejs:item/metal/double_ingot").color(0, 0x898989)
event.create('double_ingot_tin_alloy').displayName('Tin Alloy Double Ingot').texture("kubejs:item/metal/double_ingot").color(0, 0x787878)
event.create('double_ingot_titanium').displayName('Titanium Double Ingot').texture("kubejs:item/metal/double_ingot").color(0, 0x7C5A87)
event.create('double_ingot_trinium').displayName('Trinium Double Ingot').texture("kubejs:item/metal/double_ingot").color(0, 0x684F81)
event.create('double_ingot_tritanium').displayName('Tritanium Double Ingot').texture("kubejs:item/metal/double_ingot").color(0, 0x3E0000)
event.create('double_ingot_tungsten').displayName('Tungsten Double Ingot').texture("kubejs:item/metal/double_ingot").color(0, 0x202020)
event.create('double_ingot_tungsten_carbide').displayName('Tungsten Carbide Double Ingot').texture("kubejs:item/metal/double_ingot").color(0, 0x200040)
event.create('double_ingot_tungsten_steel').displayName('Tungsten Steel Double Ingot').texture("kubejs:item/metal/double_ingot").color(0, 0x404066)
event.create('double_ingot_ultimet').displayName('Ultimet Double Ingot').texture("kubejs:item/metal/double_ingot").color(0, 0x787899)
event.create('double_ingot_uranium').displayName('Uranium Double Ingot').texture("kubejs:item/metal/double_ingot").color(0, 0x1B811B)
event.create('double_ingot_uranium_235').displayName('Uranium 235 Double Ingot').texture("kubejs:item/metal/double_ingot").color(0, 0x30AC30)
event.create('double_ingot_uranium_rhodium_dinaquadide').displayName('Uranium Rhodium Dinaquadide Double Ingot').texture("kubejs:item/metal/double_ingot").color(0, 0x060606)
event.create('double_ingot_uranium_triplatinum').displayName('Uranium Triplatinum Double Ingot').texture("kubejs:item/metal/double_ingot").color(0, 0x005B00)
event.create('double_ingot_vanadium').displayName('Vanadium Double Ingot').texture("kubejs:item/metal/double_ingot").color(0, 0x202020)
event.create('double_ingot_vanadium_gallium').displayName('Vanadium Gallium Double Ingot').texture("kubejs:item/metal/double_ingot").color(0, 0x575760)
event.create('double_ingot_vanadium_steel').displayName('Vanadium Steel Double Ingot').texture("kubejs:item/metal/double_ingot").color(0, 0x7E7E7E)
event.create('double_ingot_wrought_iron').displayName('Wrought Iron Double Ingot').texture("kubejs:item/metal/double_ingot").color(0, 0x837676)
event.create('double_ingot_yttrium').displayName('Yttrium Double Ingot').texture("kubejs:item/metal/double_ingot").color(0, 0x573C38)
event.create('double_ingot_yttrium_barium_cuprate').displayName('Yttrium Barium Cuprate Double Ingot').texture("kubejs:item/metal/double_ingot").color(0, 0x342A2E)
event.create('double_ingot_zinc').displayName('Zinc Double Ingot').texture("kubejs:item/metal/double_ingot").color(0, 0x9A9AA4)
})